(function () {
  "use strict";

  const LETTER_TRANSLITERATIONS = [
    { cyrillic: "а", latin: "a", cyrillicToLatinMustAsk: ["o", "e", "u"], latinToCyrillicMustAsk: ["ъ", "о", "е", "у"] },
    { cyrillic: "б", latin: "b", cyrillicToLatinMustAsk: ["v", "d", "g"], latinToCyrillicMustAsk: ["в", "д", "г"] },
    { cyrillic: "в", latin: "v", cyrillicToLatinMustAsk: ["b", "w", "f"], latinToCyrillicMustAsk: ["б", "ъ", "ь", "ф"] },
    { cyrillic: "г", latin: "g", cyrillicToLatinMustAsk: ["r", "h", "k"], latinToCyrillicMustAsk: ["р", "х", "к"] },
    { cyrillic: "д", latin: "d", cyrillicToLatinMustAsk: ["g", "a", "t", "l"], latinToCyrillicMustAsk: ["г", "а", "ъ", "т"] },
    { cyrillic: "е", latin: "e", cyrillicToLatinMustAsk: ["i", "y", "a"], latinToCyrillicMustAsk: ["и", "й", "ь", "а"] },
    { cyrillic: "ж", latin: "zh", cyrillicToLatinMustAsk: ["sh", "ch", "z", "j"], latinToCyrillicMustAsk: ["ш", "ч", "з"] },
    { cyrillic: "з", latin: "z", cyrillicToLatinMustAsk: ["s", "e", "zh"], latinToCyrillicMustAsk: ["с", "е", "ж"] },
    { cyrillic: "и", latin: "i", cyrillicToLatinMustAsk: ["n", "u", "y"], latinToCyrillicMustAsk: ["н", "у", "й", "ь"] },
    { cyrillic: "й", latin: "y", cyrillicToLatinMustAsk: ["i", "u", "j"], latinToCyrillicMustAsk: ["ь", "и", "у"] },
    { cyrillic: "к", latin: "k", cyrillicToLatinMustAsk: ["x", "h", "q"], latinToCyrillicMustAsk: ["х"] },
    { cyrillic: "л", latin: "l", cyrillicToLatinMustAsk: ["r", "m", "n"], latinToCyrillicMustAsk: ["р", "м", "н"] },
    { cyrillic: "м", latin: "m", cyrillicToLatinMustAsk: ["n", "h", "l"], latinToCyrillicMustAsk: ["н", "х", "л"] },
    { cyrillic: "н", latin: "n", cyrillicToLatinMustAsk: ["h", "m", "u"], latinToCyrillicMustAsk: ["х", "м", "у"] },
    { cyrillic: "о", latin: "o", cyrillicToLatinMustAsk: ["a", "e", "u"], latinToCyrillicMustAsk: ["а", "ъ", "е", "у"] },
    { cyrillic: "п", latin: "p", cyrillicToLatinMustAsk: ["n", "u", "r", "b"], latinToCyrillicMustAsk: ["н", "у", "р", "б"] },
    { cyrillic: "р", latin: "r", cyrillicToLatinMustAsk: ["p", "b", "l"], latinToCyrillicMustAsk: ["п", "б", "л"] },
    { cyrillic: "с", latin: "s", cyrillicToLatinMustAsk: ["c", "z", "k"], latinToCyrillicMustAsk: ["з", "к"] },
    { cyrillic: "т", latin: "t", cyrillicToLatinMustAsk: ["m", "d", "n"], latinToCyrillicMustAsk: ["м", "д", "н"] },
    { cyrillic: "у", latin: "u", cyrillicToLatinMustAsk: ["y", "v", "w"], latinToCyrillicMustAsk: ["й", "ь", "в"] },
    { cyrillic: "ф", latin: "f", cyrillicToLatinMustAsk: ["o", "p", "v"], latinToCyrillicMustAsk: ["о", "п", "в"] },
    { cyrillic: "х", latin: "h", cyrillicToLatinMustAsk: ["x", "k", "ch"], latinToCyrillicMustAsk: ["к", "ч"] },
    { cyrillic: "ц", latin: "ts", cyrillicToLatinMustAsk: ["c", "s", "ch"], latinToCyrillicMustAsk: ["с", "ч"] },
    { cyrillic: "ч", latin: "ch", cyrillicToLatinMustAsk: ["sh", "ts", "c"], latinToCyrillicMustAsk: ["ш", "ц"] },
    { cyrillic: "ш", latin: "sh", cyrillicToLatinMustAsk: ["ch", "sht", "s"], latinToCyrillicMustAsk: ["ч", "щ", "с"] },
    { cyrillic: "щ", latin: "sht", cyrillicToLatinMustAsk: ["sh", "ch", "ts"], latinToCyrillicMustAsk: ["ш", "ч", "ц"] },
    { cyrillic: "ъ", latin: "a", cyrillicToLatinMustAsk: ["u", "y", "o"], latinToCyrillicMustAsk: ["а", "у", "й", "ь"] },
    { cyrillic: "ь", latin: "y", cyrillicToLatinMustAsk: ["b", "i", "u"], latinToCyrillicMustAsk: ["й", "б", "и", "у"] },
    { cyrillic: "ю", latin: "yu", cyrillicToLatinMustAsk: ["u", "ya", "y"], latinToCyrillicMustAsk: ["у", "я", "й", "ь"] },
    { cyrillic: "я", latin: "ya", cyrillicToLatinMustAsk: ["r", "a", "yu"], latinToCyrillicMustAsk: ["р", "а", "ъ", "ю"] },
    { cyrillic: "А", latin: "A", cyrillicToLatinMustAsk: ["O", "E", "U"], latinToCyrillicMustAsk: ["Ъ", "О", "Е", "У"] },
    { cyrillic: "Б", latin: "B", cyrillicToLatinMustAsk: ["V", "D", "G"], latinToCyrillicMustAsk: ["В", "Д", "Г"] },
    { cyrillic: "В", latin: "V", cyrillicToLatinMustAsk: ["B", "W", "F"], latinToCyrillicMustAsk: ["Б", "Ъ", "Ь", "Ф"] },
    { cyrillic: "Г", latin: "G", cyrillicToLatinMustAsk: ["L", "T", "K"], latinToCyrillicMustAsk: ["Л", "Т", "К"] },
    { cyrillic: "Д", latin: "D", cyrillicToLatinMustAsk: ["A", "L", "G", "T"], latinToCyrillicMustAsk: ["А", "Ъ", "Л", "Г"] },
    { cyrillic: "Е", latin: "E", cyrillicToLatinMustAsk: ["I", "Y", "A"], latinToCyrillicMustAsk: ["И", "Й", "Ь", "А"] },
    { cyrillic: "Ж", latin: "ZH", cyrillicToLatinMustAsk: ["SH", "CH", "Z", "J"], latinToCyrillicMustAsk: ["Ш", "Ч", "З"] },
    { cyrillic: "З", latin: "Z", cyrillicToLatinMustAsk: ["S", "E", "ZH"], latinToCyrillicMustAsk: ["С", "Е", "Ж"] },
    { cyrillic: "И", latin: "I", cyrillicToLatinMustAsk: ["N", "U", "Y"], latinToCyrillicMustAsk: ["Н", "У", "Й", "Ь"] },
    { cyrillic: "Й", latin: "Y", cyrillicToLatinMustAsk: ["I", "N", "U"], latinToCyrillicMustAsk: ["Ь", "И", "Н", "У"] },
    { cyrillic: "К", latin: "K", cyrillicToLatinMustAsk: ["X", "H", "Q"], latinToCyrillicMustAsk: ["Х"] },
    { cyrillic: "Л", latin: "L", cyrillicToLatinMustAsk: ["A", "M", "N"], latinToCyrillicMustAsk: ["А", "Ъ", "М", "Н"] },
    { cyrillic: "М", latin: "M", cyrillicToLatinMustAsk: ["N", "H", "L"], latinToCyrillicMustAsk: ["Н", "Х", "Л"] },
    { cyrillic: "Н", latin: "N", cyrillicToLatinMustAsk: ["H", "M", "U"], latinToCyrillicMustAsk: ["Х", "М", "У"] },
    { cyrillic: "О", latin: "O", cyrillicToLatinMustAsk: ["A", "E", "U"], latinToCyrillicMustAsk: ["А", "Ъ", "Е", "У"] },
    { cyrillic: "П", latin: "P", cyrillicToLatinMustAsk: ["N", "U", "R", "B"], latinToCyrillicMustAsk: ["Н", "У", "Р", "Б"] },
    { cyrillic: "Р", latin: "R", cyrillicToLatinMustAsk: ["P", "B", "L"], latinToCyrillicMustAsk: ["П", "Б", "Л"] },
    { cyrillic: "С", latin: "S", cyrillicToLatinMustAsk: ["C", "Z", "K"], latinToCyrillicMustAsk: ["З", "К"] },
    { cyrillic: "Т", latin: "T", cyrillicToLatinMustAsk: ["M", "D", "N"], latinToCyrillicMustAsk: ["М", "Д", "Н"] },
    { cyrillic: "У", latin: "U", cyrillicToLatinMustAsk: ["Y", "V", "W"], latinToCyrillicMustAsk: ["Й", "Ь", "В"] },
    { cyrillic: "Ф", latin: "F", cyrillicToLatinMustAsk: ["O", "P", "V"], latinToCyrillicMustAsk: ["О", "П", "В"] },
    { cyrillic: "Х", latin: "H", cyrillicToLatinMustAsk: ["X", "K", "CH"], latinToCyrillicMustAsk: ["К", "Ч"] },
    { cyrillic: "Ц", latin: "TS", cyrillicToLatinMustAsk: ["C", "S", "CH", "U"], latinToCyrillicMustAsk: ["С", "Ч", "У"] },
    { cyrillic: "Ч", latin: "CH", cyrillicToLatinMustAsk: ["SH", "TS", "C"], latinToCyrillicMustAsk: ["Ш", "Ц"] },
    { cyrillic: "Ш", latin: "SH", cyrillicToLatinMustAsk: ["W", "CH", "SHT", "S"], latinToCyrillicMustAsk: ["Ч", "Щ", "С"] },
    { cyrillic: "Щ", latin: "SHT", cyrillicToLatinMustAsk: ["W", "SH", "CH", "TS"], latinToCyrillicMustAsk: ["Ш", "Ч", "Ц"] },
    { cyrillic: "Ъ", latin: "A", cyrillicToLatinMustAsk: ["B", "U", "Y", "O"], latinToCyrillicMustAsk: ["А", "Б", "У", "Й"] },
    { cyrillic: "Ь", latin: "Y", cyrillicToLatinMustAsk: ["B", "I", "U"], latinToCyrillicMustAsk: ["Й", "Б", "И", "У"] },
    { cyrillic: "Ю", latin: "YU", cyrillicToLatinMustAsk: ["U", "YA", "Y", "O"], latinToCyrillicMustAsk: ["У", "Я", "Й", "Ь"] },
    { cyrillic: "Я", latin: "YA", cyrillicToLatinMustAsk: ["R", "A", "YU"], latinToCyrillicMustAsk: ["Р", "А", "Ъ", "Ю"] }
  ];

  const LETTER_OPTIONS = [
    "a",
    "b",
    "c",
    "ch",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "p",
    "q",
    "r",
    "s",
    "sh",
    "sht",
    "t",
    "ts",
    "u",
    "v",
    "w",
    "x",
    "y",
    "ya",
    "yu",
    "z",
    "zh"
  ];

  const WORD_SOURCE = [
    { rank: 1, cyrillic: "да", latin: "da", phonetic: "da", englishMeaning: "yes" },
    { rank: 2, cyrillic: "е", latin: "e", phonetic: "eh", englishMeaning: "is" },
    { rank: 3, cyrillic: "не", latin: "ne", phonetic: "neh", englishMeaning: "no, not" },
    { rank: 4, cyrillic: "се", latin: "se", phonetic: "seh", englishMeaning: "self, reflexive particle" },
    { rank: 5, cyrillic: "и", latin: "i", phonetic: "ee", englishMeaning: "and" },
    { rank: 6, cyrillic: "на", latin: "na", phonetic: "na", englishMeaning: "of, on, to" },
    { rank: 7, cyrillic: "си", latin: "si", phonetic: "see", englishMeaning: "oneself, own" },
    { rank: 8, cyrillic: "за", latin: "za", phonetic: "za", englishMeaning: "for, about" },
    { rank: 9, cyrillic: "ще", latin: "shte", phonetic: "shteh", englishMeaning: "will" },
    { rank: 10, cyrillic: "че", latin: "che", phonetic: "cheh", englishMeaning: "that" },
    { rank: 11, cyrillic: "това", latin: "tova", phonetic: "tova", englishMeaning: "this, that" },
    { rank: 12, cyrillic: "ли", latin: "li", phonetic: "lee", englishMeaning: "question particle" },
    { rank: 13, cyrillic: "в", latin: "v", phonetic: "v", englishMeaning: "in" },
    { rank: 14, cyrillic: "ти", latin: "ti", phonetic: "tee", englishMeaning: "you" },
    { rank: 15, cyrillic: "от", latin: "ot", phonetic: "ot", englishMeaning: "from, by" },
    { rank: 16, cyrillic: "ми", latin: "mi", phonetic: "mee", englishMeaning: "my, to me" },
    { rank: 17, cyrillic: "с", latin: "s", phonetic: "s", englishMeaning: "with" },
    { rank: 18, cyrillic: "какво", latin: "kakvo", phonetic: "kakvo", englishMeaning: "what" },
    { rank: 19, cyrillic: "го", latin: "go", phonetic: "go", englishMeaning: "him, it" },
    { rank: 20, cyrillic: "съм", latin: "sam", phonetic: "suhm", englishMeaning: "I am" },
    { rank: 21, cyrillic: "но", latin: "no", phonetic: "no", englishMeaning: "but" },
    { rank: 22, cyrillic: "аз", latin: "az", phonetic: "az", englishMeaning: "I" },
    { rank: 23, cyrillic: "те", latin: "te", phonetic: "teh", englishMeaning: "they, them" },
    { rank: 24, cyrillic: "трябва", latin: "tryabva", phonetic: "tryabva", englishMeaning: "must, should" },
    { rank: 25, cyrillic: "добре", latin: "dobre", phonetic: "dobreh", englishMeaning: "well, good" },
    { rank: 26, cyrillic: "ме", latin: "me", phonetic: "meh", englishMeaning: "me" },
    { rank: 27, cyrillic: "са", latin: "sa", phonetic: "sa", englishMeaning: "are" },
    { rank: 28, cyrillic: "няма", latin: "nyama", phonetic: "nyama", englishMeaning: "there is no, will not" },
    { rank: 29, cyrillic: "може", latin: "mozhe", phonetic: "mozheh", englishMeaning: "can, may" },
    { rank: 30, cyrillic: "ако", latin: "ako", phonetic: "ako", englishMeaning: "if" },
    { rank: 31, cyrillic: "тук", latin: "tuk", phonetic: "took", englishMeaning: "here" },
    { rank: 32, cyrillic: "така", latin: "taka", phonetic: "taka", englishMeaning: "so, like this" },
    { rank: 33, cyrillic: "а", latin: "a", phonetic: "a", englishMeaning: "and, but" },
    { rank: 34, cyrillic: "ви", latin: "vi", phonetic: "vee", englishMeaning: "you, your" },
    { rank: 35, cyrillic: "като", latin: "kato", phonetic: "kato", englishMeaning: "as, like" },
    { rank: 36, cyrillic: "много", latin: "mnogo", phonetic: "mnogo", englishMeaning: "much, many, very" },
    { rank: 37, cyrillic: "той", latin: "toy", phonetic: "toy", englishMeaning: "he" },
    { rank: 38, cyrillic: "по", latin: "po", phonetic: "po", englishMeaning: "along, by, more" },
    { rank: 39, cyrillic: "има", latin: "ima", phonetic: "eema", englishMeaning: "there is, has" },
    { rank: 40, cyrillic: "беше", latin: "beshe", phonetic: "behsheh", englishMeaning: "was" },
    { rank: 41, cyrillic: "нещо", latin: "neshto", phonetic: "nehshto", englishMeaning: "something" },
    { rank: 42, cyrillic: "му", latin: "mu", phonetic: "moo", englishMeaning: "his, to him" },
    { rank: 43, cyrillic: "как", latin: "kak", phonetic: "kak", englishMeaning: "how" },
    { rank: 44, cyrillic: "защо", latin: "zashto", phonetic: "zashto", englishMeaning: "why" },
    { rank: 45, cyrillic: "ни", latin: "ni", phonetic: "nee", englishMeaning: "us, our" },
    { rank: 46, cyrillic: "я", latin: "ya", phonetic: "ya", englishMeaning: "her, it" },
    { rank: 47, cyrillic: "знам", latin: "znam", phonetic: "znam", englishMeaning: "I know" },
    { rank: 48, cyrillic: "само", latin: "samo", phonetic: "samo", englishMeaning: "only" },
    { rank: 49, cyrillic: "всичко", latin: "vsichko", phonetic: "vseechko", englishMeaning: "everything" },
    { rank: 50, cyrillic: "мен", latin: "men", phonetic: "mehn", englishMeaning: "me" },
    { rank: 51, cyrillic: "сега", latin: "sega", phonetic: "sehga", englishMeaning: "now" },
    { rank: 52, cyrillic: "теб", latin: "teb", phonetic: "tehb", englishMeaning: "you" },
    { rank: 53, cyrillic: "тя", latin: "tya", phonetic: "tya", englishMeaning: "she" },
    { rank: 54, cyrillic: "което", latin: "koeto", phonetic: "koehto", englishMeaning: "which, that" },
    { rank: 55, cyrillic: "искам", latin: "iskam", phonetic: "eeskam", englishMeaning: "I want" },
    { rank: 56, cyrillic: "мога", latin: "moga", phonetic: "moga", englishMeaning: "I can" },
    { rank: 57, cyrillic: "още", latin: "oshte", phonetic: "oshteh", englishMeaning: "more, still, yet" },
    { rank: 58, cyrillic: "когато", latin: "kogato", phonetic: "kogato", englishMeaning: "when" },
    { rank: 59, cyrillic: "до", latin: "do", phonetic: "do", englishMeaning: "to, until" },
    { rank: 60, cyrillic: "ги", latin: "gi", phonetic: "gee", englishMeaning: "them" },
    { rank: 61, cyrillic: "този", latin: "tozi", phonetic: "tozee", englishMeaning: "this" },
    { rank: 62, cyrillic: "просто", latin: "prosto", phonetic: "prosto", englishMeaning: "simply, just" },
    { rank: 63, cyrillic: "сте", latin: "ste", phonetic: "steh", englishMeaning: "you are" },
    { rank: 64, cyrillic: "или", latin: "ili", phonetic: "eelee", englishMeaning: "or" },
    { rank: 65, cyrillic: "къде", latin: "kade", phonetic: "kuh-'deh", englishMeaning: "where" },
    { rank: 66, cyrillic: "би", latin: "bi", phonetic: "bee", englishMeaning: "would" },
    { rank: 67, cyrillic: "тази", latin: "tazi", phonetic: "tazee", englishMeaning: "this" },
    { rank: 68, cyrillic: "всички", latin: "vsichki", phonetic: "vseechkee", englishMeaning: "all, everyone" },
    { rank: 69, cyrillic: "благодаря", latin: "blagodarya", phonetic: "blagodarya", englishMeaning: "thank you" },
    { rank: 70, cyrillic: "нали", latin: "nali", phonetic: "nalee", englishMeaning: "right, is it not" },
    { rank: 71, cyrillic: "сме", latin: "sme", phonetic: "smeh", englishMeaning: "we are" },
    { rank: 72, cyrillic: "нищо", latin: "nishto", phonetic: "neeshto", englishMeaning: "nothing" },
    { rank: 73, cyrillic: "толкова", latin: "tolkova", phonetic: "tolkova", englishMeaning: "so much" },
    { rank: 74, cyrillic: "знаеш", latin: "znaesh", phonetic: "znaehsh", englishMeaning: "you know" },
    { rank: 75, cyrillic: "един", latin: "edin", phonetic: "ehdeen", englishMeaning: "one, a" },
    { rank: 76, cyrillic: "защото", latin: "zashtoto", phonetic: "zashtoto", englishMeaning: "because" },
    { rank: 77, cyrillic: "след", latin: "sled", phonetic: "slehd", englishMeaning: "after" },
    { rank: 78, cyrillic: "там", latin: "tam", phonetic: "tam", englishMeaning: "there" },
    { rank: 79, cyrillic: "време", latin: "vreme", phonetic: "vrehmeh", englishMeaning: "time, weather" },
    { rank: 80, cyrillic: "който", latin: "koyto", phonetic: "koyto", englishMeaning: "who, which" },
    { rank: 81, cyrillic: "искаш", latin: "iskash", phonetic: "eeskash", englishMeaning: "you want" },
    { rank: 82, cyrillic: "мисля", latin: "mislya", phonetic: "meeslya", englishMeaning: "I think" },
    { rank: 83, cyrillic: "кой", latin: "koy", phonetic: "koy", englishMeaning: "who" },
    { rank: 84, cyrillic: "малко", latin: "malko", phonetic: "malko", englishMeaning: "little, a little" },
    { rank: 85, cyrillic: "имам", latin: "imam", phonetic: "eemam", englishMeaning: "I have" },
    { rank: 86, cyrillic: "преди", latin: "predi", phonetic: "prehdee", englishMeaning: "before" },
    { rank: 87, cyrillic: "хайде", latin: "hayde", phonetic: "khaydeh", englishMeaning: "come on" },
    { rank: 88, cyrillic: "вече", latin: "veche", phonetic: "vehcheh", englishMeaning: "already" },
    { rank: 89, cyrillic: "тези", latin: "tezi", phonetic: "tehzee", englishMeaning: "these" },
    { rank: 90, cyrillic: "моля", latin: "molya", phonetic: "molya", englishMeaning: "please" },
    { rank: 91, cyrillic: "о", latin: "o", phonetic: "o", englishMeaning: "oh" },
    { rank: 92, cyrillic: "някой", latin: "nyakoy", phonetic: "nyakoy", englishMeaning: "someone" },
    { rank: 93, cyrillic: "каза", latin: "kaza", phonetic: "kaza", englishMeaning: "said" },
    { rank: 94, cyrillic: "него", latin: "nego", phonetic: "nehgo", englishMeaning: "him" },
    { rank: 95, cyrillic: "наистина", latin: "naistina", phonetic: "naeesteena", englishMeaning: "really, truly" },
    { rank: 96, cyrillic: "ние", latin: "nie", phonetic: "neeeh", englishMeaning: "we" },
    { rank: 97, cyrillic: "вие", latin: "vie", phonetic: "veeeh", englishMeaning: "you" },
    { rank: 98, cyrillic: "които", latin: "koito", phonetic: "koeeto", englishMeaning: "who, which" },
    { rank: 99, cyrillic: "й", latin: "y", phonetic: "y", englishMeaning: "her, to her" },
    { rank: 100, cyrillic: "повече", latin: "poveche", phonetic: "povehcheh", englishMeaning: "more" },
    { rank: 101, cyrillic: "съжалявам", latin: "sazhalyavam", phonetic: "suhzhalyavam", englishMeaning: "I am sorry" },
    { rank: 102, cyrillic: "тогава", latin: "togava", phonetic: "togava", englishMeaning: "then" },
    { rank: 103, cyrillic: "точно", latin: "tochno", phonetic: "tochno", englishMeaning: "exactly" },
    { rank: 104, cyrillic: "става", latin: "stava", phonetic: "stava", englishMeaning: "happens, becomes" },
    { rank: 105, cyrillic: "все", latin: "vse", phonetic: "vseh", englishMeaning: "still, always" },
    { rank: 106, cyrillic: "можеш", latin: "mozhesh", phonetic: "mozhehsh", englishMeaning: "you can" },
    { rank: 107, cyrillic: "една", latin: "edna", phonetic: "ehdna", englishMeaning: "one, a" },
    { rank: 108, cyrillic: "имаш", latin: "imash", phonetic: "eemash", englishMeaning: "you have" },
    { rank: 109, cyrillic: "към", latin: "kam", phonetic: "kuhm", englishMeaning: "toward" },
    { rank: 110, cyrillic: "без", latin: "bez", phonetic: "behz", englishMeaning: "without" },
    { rank: 111, cyrillic: "колко", latin: "kolko", phonetic: "kolko", englishMeaning: "how much, how many" },
    { rank: 112, cyrillic: "кажа", latin: "kazha", phonetic: "kazha", englishMeaning: "I say, I will say" },
    { rank: 113, cyrillic: "никога", latin: "nikoga", phonetic: "neekoga", englishMeaning: "never" },
    { rank: 114, cyrillic: "при", latin: "pri", phonetic: "pree", englishMeaning: "at, near, with" },
    { rank: 115, cyrillic: "човек", latin: "chovek", phonetic: "chovehk", englishMeaning: "person, man" },
    { rank: 116, cyrillic: "работа", latin: "rabota", phonetic: "rabota", englishMeaning: "work, job" },
    { rank: 117, cyrillic: "им", latin: "im", phonetic: "eem", englishMeaning: "them, their" },
    { rank: 118, cyrillic: "ден", latin: "den", phonetic: "dehn", englishMeaning: "day" },
    { rank: 119, cyrillic: "едно", latin: "edno", phonetic: "ehdno", englishMeaning: "one, a" },
    { rank: 120, cyrillic: "бях", latin: "byah", phonetic: "byakh", englishMeaning: "I was" },
    { rank: 121, cyrillic: "бъде", latin: "bade", phonetic: "buhdeh", englishMeaning: "be, become" },
    { rank: 122, cyrillic: "през", latin: "prez", phonetic: "prehz", englishMeaning: "through, during" },
    { rank: 123, cyrillic: "ето", latin: "eto", phonetic: "ehto", englishMeaning: "here is" },
    { rank: 124, cyrillic: "значи", latin: "znachi", phonetic: "znachee", englishMeaning: "means, so" },
    { rank: 125, cyrillic: "със", latin: "sas", phonetic: "suhs", englishMeaning: "with" },
    { rank: 126, cyrillic: "дори", latin: "dori", phonetic: "doree", englishMeaning: "even" },
    { rank: 127, cyrillic: "хора", latin: "hora", phonetic: "khora", englishMeaning: "people" },
    { rank: 128, cyrillic: "път", latin: "pat", phonetic: "puht", englishMeaning: "road, time" },
    { rank: 129, cyrillic: "както", latin: "kakto", phonetic: "kakto", englishMeaning: "as, like" },
    { rank: 130, cyrillic: "нас", latin: "nas", phonetic: "nas", englishMeaning: "us" },
    { rank: 131, cyrillic: "години", latin: "godini", phonetic: "godeenee", englishMeaning: "years" },
    { rank: 132, cyrillic: "бил", latin: "bil", phonetic: "beel", englishMeaning: "was, has been" },
    { rank: 133, cyrillic: "баща", latin: "bashta", phonetic: "bashta", englishMeaning: "father" },
    { rank: 134, cyrillic: "правиш", latin: "pravish", phonetic: "praveesh", englishMeaning: "you do, you make" },
    { rank: 135, cyrillic: "която", latin: "koyato", phonetic: "koyato", englishMeaning: "who, which" },
    { rank: 136, cyrillic: "разбира", latin: "razbira", phonetic: "razbeera", englishMeaning: "understands" },
    { rank: 137, cyrillic: "също", latin: "sashto", phonetic: "suhshto", englishMeaning: "also" },
    { rank: 138, cyrillic: "мислиш", latin: "mislish", phonetic: "meesleesh", englishMeaning: "you think" },
    { rank: 139, cyrillic: "вас", latin: "vas", phonetic: "vas", englishMeaning: "you" },
    { rank: 140, cyrillic: "ами", latin: "ami", phonetic: "amee", englishMeaning: "well" },
    { rank: 141, cyrillic: "нея", latin: "neya", phonetic: "nehya", englishMeaning: "her" },
    { rank: 142, cyrillic: "направи", latin: "napravi", phonetic: "napravee", englishMeaning: "made, did" },
    { rank: 143, cyrillic: "винаги", latin: "vinagi", phonetic: "veenagee", englishMeaning: "always" },
    { rank: 144, cyrillic: "докато", latin: "dokato", phonetic: "dokato", englishMeaning: "while, until" },
    { rank: 145, cyrillic: "имаме", latin: "imame", phonetic: "eemameh", englishMeaning: "we have" },
    { rank: 146, cyrillic: "виж", latin: "vizh", phonetic: "veezh", englishMeaning: "look, see" },
    { rank: 147, cyrillic: "всеки", latin: "vseki", phonetic: "vsehkee", englishMeaning: "every, everyone" },
    { rank: 148, cyrillic: "иска", latin: "iska", phonetic: "eeska", englishMeaning: "wants" },
    { rank: 149, cyrillic: "майка", latin: "mayka", phonetic: "mayka", englishMeaning: "mother" },
    { rank: 150, cyrillic: "казах", latin: "kazah", phonetic: "kazakh", englishMeaning: "I said" },
    { rank: 151, cyrillic: "нека", latin: "neka", phonetic: "nehka", englishMeaning: "let" },
    { rank: 152, cyrillic: "хората", latin: "horata", phonetic: "khorata", englishMeaning: "the people" },
    { rank: 153, cyrillic: "хей", latin: "hey", phonetic: "khehy", englishMeaning: "hey" },
    { rank: 154, cyrillic: "жена", latin: "zhena", phonetic: "zhehna", englishMeaning: "woman, wife" },
    { rank: 155, cyrillic: "видя", latin: "vidya", phonetic: "veedya", englishMeaning: "saw, see" },
    { rank: 156, cyrillic: "дали", latin: "dali", phonetic: "dalee", englishMeaning: "whether" },
    { rank: 157, cyrillic: "във", latin: "vav", phonetic: "vuhv", englishMeaning: "in" },
    { rank: 158, cyrillic: "никой", latin: "nikoy", phonetic: "neekoy", englishMeaning: "nobody" },
    { rank: 159, cyrillic: "пак", latin: "pak", phonetic: "pak", englishMeaning: "again" },
    { rank: 160, cyrillic: "тях", latin: "tyah", phonetic: "tyakh", englishMeaning: "them" },
    { rank: 161, cyrillic: "направя", latin: "napravya", phonetic: "napravya", englishMeaning: "I make, I do" },
    { rank: 162, cyrillic: "неща", latin: "neshta", phonetic: "nehshta", englishMeaning: "things" },
    { rank: 163, cyrillic: "кажи", latin: "kazhi", phonetic: "kazhee", englishMeaning: "say, tell" },
    { rank: 164, cyrillic: "място", latin: "myasto", phonetic: "myasto", englishMeaning: "place" },
    { rank: 165, cyrillic: "заради", latin: "zaradi", phonetic: "zaradee", englishMeaning: "because of" },
    { rank: 166, cyrillic: "прави", latin: "pravi", phonetic: "pravee", englishMeaning: "does, makes" },
    { rank: 167, cyrillic: "сър", latin: "sar", phonetic: "suhr", englishMeaning: "sir" },
    { rank: 168, cyrillic: "можем", latin: "mozhem", phonetic: "mozhehm", englishMeaning: "we can" },
    { rank: 169, cyrillic: "дяволите", latin: "dyavolite", phonetic: "dyavoleeteh", englishMeaning: "the devils, damn" },
    { rank: 170, cyrillic: "изглежда", latin: "izglezhda", phonetic: "eezglehzhda", englishMeaning: "seems, looks" },
    { rank: 171, cyrillic: "днес", latin: "dnes", phonetic: "dnehs", englishMeaning: "today" },
    { rank: 172, cyrillic: "кажеш", latin: "kazhesh", phonetic: "kazhehsh", englishMeaning: "you say, you tell" },
    { rank: 173, cyrillic: "живота", latin: "zhivota", phonetic: "zheevota", englishMeaning: "the life" },
    { rank: 174, cyrillic: "трябваше", latin: "tryabvashe", phonetic: "tryabvasheh", englishMeaning: "had to, should have" },
    { rank: 175, cyrillic: "отново", latin: "otnovo", phonetic: "otnovo", englishMeaning: "again" },
    { rank: 176, cyrillic: "татко", latin: "tatko", phonetic: "tatko", englishMeaning: "dad" },
    { rank: 177, cyrillic: "няколко", latin: "nyakolko", phonetic: "nyakolko", englishMeaning: "several" },
    { rank: 178, cyrillic: "наред", latin: "nared", phonetic: "narehd", englishMeaning: "in order, for" },
    { rank: 179, cyrillic: "боже", latin: "bozhe", phonetic: "bozheh", englishMeaning: "God, oh God" },
    { rank: 180, cyrillic: "друг", latin: "drug", phonetic: "droog", englishMeaning: "other, another" },
    { rank: 181, cyrillic: "здравей", latin: "zdravey", phonetic: "zdravehy", englishMeaning: "hello" },
    { rank: 182, cyrillic: "затова", latin: "zatova", phonetic: "zatova", englishMeaning: "therefore, that is why" },
    { rank: 183, cyrillic: "бих", latin: "bih", phonetic: "beekh", englishMeaning: "would" },
    { rank: 184, cyrillic: "доста", latin: "dosta", phonetic: "dosta", englishMeaning: "quite, enough" },
    { rank: 185, cyrillic: "обичам", latin: "obicham", phonetic: "obeecham", englishMeaning: "I love" },
    { rank: 186, cyrillic: "пари", latin: "pari", phonetic: "paree", englishMeaning: "money" },
    { rank: 187, cyrillic: "знае", latin: "znae", phonetic: "znaeh", englishMeaning: "knows" },
    { rank: 188, cyrillic: "начин", latin: "nachin", phonetic: "nacheen", englishMeaning: "way" },
    { rank: 189, cyrillic: "моя", latin: "moya", phonetic: "moya", englishMeaning: "my" },
    { rank: 190, cyrillic: "мислех", latin: "misleh", phonetic: "meeslehkh", englishMeaning: "I thought" },
    { rank: 191, cyrillic: "нужда", latin: "nuzhda", phonetic: "noozhda", englishMeaning: "need" },
    { rank: 192, cyrillic: "сам", latin: "sam", phonetic: "sam", englishMeaning: "alone, by myself" },
    { rank: 193, cyrillic: "две", latin: "dve", phonetic: "dveh", englishMeaning: "two" },
    { rank: 194, cyrillic: "дойде", latin: "doyde", phonetic: "doydeh", englishMeaning: "came" },
    { rank: 195, cyrillic: "заедно", latin: "zaedno", phonetic: "zaehdno", englishMeaning: "together" },
    { rank: 196, cyrillic: "добър", latin: "dobar", phonetic: "dobuhr", englishMeaning: "good" },
    { rank: 197, cyrillic: "ела", latin: "ela", phonetic: "ehla", englishMeaning: "come" },
    { rank: 198, cyrillic: "нямам", latin: "nyamam", phonetic: "nyamam", englishMeaning: "I do not have" },
    { rank: 199, cyrillic: "приятел", latin: "priyatel", phonetic: "preeyatehl", englishMeaning: "friend" },
    { rank: 200, cyrillic: "после", latin: "posle", phonetic: "posleh", englishMeaning: "afterwards, later" },
    { rank: 201, cyrillic: "видим", latin: "vidim", phonetic: "veedeem", englishMeaning: "we see, visible" },
    { rank: 202, cyrillic: "правя", latin: "pravya", phonetic: "pravya", englishMeaning: "I do, I make" },
    { rank: 203, cyrillic: "вечер", latin: "vecher", phonetic: "vehchehr", englishMeaning: "evening" },
    { rank: 204, cyrillic: "достатъчно", latin: "dostatachno", phonetic: "dostatuhchno", englishMeaning: "enough" },
    { rank: 205, cyrillic: "всъщност", latin: "vsashtnost", phonetic: "vsuhshtnost", englishMeaning: "actually" },
    { rank: 206, cyrillic: "исках", latin: "iskah", phonetic: "eeskakh", englishMeaning: "I wanted" },
    { rank: 207, cyrillic: "проблем", latin: "problem", phonetic: "problehm", englishMeaning: "problem" },
    { rank: 208, cyrillic: "живот", latin: "zhivot", phonetic: "zheevot", englishMeaning: "life" },
    { rank: 209, cyrillic: "нещата", latin: "neshtata", phonetic: "nehshtata", englishMeaning: "the things" },
    { rank: 210, cyrillic: "под", latin: "pod", phonetic: "pod", englishMeaning: "under" },
    { rank: 211, cyrillic: "каквото", latin: "kakvoto", phonetic: "kakvoto", englishMeaning: "whatever, what" },
    { rank: 212, cyrillic: "говори", latin: "govori", phonetic: "govoree", englishMeaning: "speaks, talk" },
    { rank: 213, cyrillic: "разбирам", latin: "razbiram", phonetic: "razbeeram", englishMeaning: "I understand" },
    { rank: 214, cyrillic: "сигурно", latin: "sigurno", phonetic: "seegoorno", englishMeaning: "probably, surely" },
    { rank: 215, cyrillic: "чакай", latin: "chakay", phonetic: "chakay", englishMeaning: "wait" },
    { rank: 216, cyrillic: "веднага", latin: "vednaga", phonetic: "vehdnaga", englishMeaning: "immediately" },
    { rank: 217, cyrillic: "ей", latin: "ey", phonetic: "ehy", englishMeaning: "hey" },
    { rank: 218, cyrillic: "три", latin: "tri", phonetic: "tree", englishMeaning: "three" },
    { rank: 219, cyrillic: "какъв", latin: "kakav", phonetic: "kakuhv", englishMeaning: "what kind of" },
    { rank: 220, cyrillic: "казва", latin: "kazva", phonetic: "kazva", englishMeaning: "says" },
    { rank: 221, cyrillic: "стана", latin: "stana", phonetic: "stana", englishMeaning: "became, happened" },
    { rank: 222, cyrillic: "утре", latin: "utre", phonetic: "ootreh", englishMeaning: "tomorrow" },
    { rank: 223, cyrillic: "дай", latin: "day", phonetic: "day", englishMeaning: "give" },
    { rank: 224, cyrillic: "добро", latin: "dobro", phonetic: "dobro", englishMeaning: "good" },
    { rank: 225, cyrillic: "знаете", latin: "znaete", phonetic: "znaehteh", englishMeaning: "you know" },
    { rank: 226, cyrillic: "говоря", latin: "govorya", phonetic: "govorya", englishMeaning: "I speak" },
    { rank: 227, cyrillic: "била", latin: "bila", phonetic: "beela", englishMeaning: "was, has been" },
    { rank: 228, cyrillic: "предвид", latin: "predvid", phonetic: "prehdveed", englishMeaning: "in mind" },
    { rank: 229, cyrillic: "казвам", latin: "kazvam", phonetic: "kazvam", englishMeaning: "I say" },
    { rank: 230, cyrillic: "колата", latin: "kolata", phonetic: "kolata", englishMeaning: "the car" },
    { rank: 231, cyrillic: "имате", latin: "imate", phonetic: "eemateh", englishMeaning: "you have" },
    { rank: 232, cyrillic: "себе", latin: "sebe", phonetic: "sehbeh", englishMeaning: "self" },
    { rank: 233, cyrillic: "момиче", latin: "momiche", phonetic: "momeecheh", englishMeaning: "girl" },
    { rank: 234, cyrillic: "мамо", latin: "mamo", phonetic: "mamo", englishMeaning: "mom" },
    { rank: 235, cyrillic: "стане", latin: "stane", phonetic: "staneh", englishMeaning: "becomes, happens" },
    { rank: 236, cyrillic: "харесва", latin: "haresva", phonetic: "kharehsva", englishMeaning: "likes" },
    { rank: 237, cyrillic: "случи", latin: "sluchi", phonetic: "sloochee", englishMeaning: "happened" },
    { rank: 238, cyrillic: "нощ", latin: "nosht", phonetic: "nosht", englishMeaning: "night" },
    { rank: 239, cyrillic: "било", latin: "bilo", phonetic: "beelo", englishMeaning: "was, has been" },
    { rank: 240, cyrillic: "работата", latin: "rabotata", phonetic: "rabotata", englishMeaning: "the work, the job" },
    { rank: 241, cyrillic: "каква", latin: "kakva", phonetic: "kakva", englishMeaning: "what kind of" },
    { rank: 242, cyrillic: "говориш", latin: "govorish", phonetic: "govoreesh", englishMeaning: "you speak" },
    { rank: 243, cyrillic: "бе", latin: "be", phonetic: "beh", englishMeaning: "was, hey" },
    { rank: 244, cyrillic: "сигурен", latin: "siguren", phonetic: "seegoorehn", englishMeaning: "sure" },
    { rank: 245, cyrillic: "искате", latin: "iskate", phonetic: "eeskateh", englishMeaning: "you want" },
    { rank: 246, cyrillic: "скъпа", latin: "skapa", phonetic: "skuhpa", englishMeaning: "dear, expensive" },
    { rank: 247, cyrillic: "филм", latin: "film", phonetic: "feelm", englishMeaning: "film" },
    { rank: 248, cyrillic: "цена", latin: "tsena", phonetic: "tsehna", englishMeaning: "price" },
    { rank: 249, cyrillic: "любов", latin: "lyubov", phonetic: "lyubov", englishMeaning: "love" },
    { rank: 250, cyrillic: "шофьор", latin: "shofyor", phonetic: "shofyor", englishMeaning: "driver" }
  ];

  const HIKING_WORD_SOURCE = [
    { rank: 1, cyrillic: "влак", latin: "vlak", phonetic: "vlak", englishMeaning: "train" },
    { rank: 2, cyrillic: "автобус", latin: "avtobus", phonetic: "avtoboos", englishMeaning: "bus" },
    { rank: 3, cyrillic: "закъснение", latin: "zakasnenie", phonetic: "zakuhsnehneeeh", englishMeaning: "delay" },
    { rank: 4, cyrillic: "спешен случай", latin: "speshen sluchay", phonetic: "spehshehn sloochay", englishMeaning: "emergency" },
    { rank: 5, cyrillic: "гръм", latin: "gram", phonetic: "gruhm", englishMeaning: "thunder" },
    { rank: 6, cyrillic: "лошо време", latin: "losho vreme", phonetic: "losho vrehmeh", englishMeaning: "bad weather" },
    { rank: 7, cyrillic: "крака", latin: "kraka", phonetic: "kraka", englishMeaning: "feet" },
    { rank: 8, cyrillic: "уморен", latin: "umoren", phonetic: "oomorehn", englishMeaning: "tired" },
    { rank: 9, cyrillic: "отпочинал", latin: "otpochinal", phonetic: "otpocheenal", englishMeaning: "well rested" },
    { rank: 10, cyrillic: "свеж", latin: "svezh", phonetic: "svehzh", englishMeaning: "fresh" },
    { rank: 11, cyrillic: "вода", latin: "voda", phonetic: "voda", englishMeaning: "water" },
    { rank: 12, cyrillic: "планина", latin: "planina", phonetic: "planeena", englishMeaning: "mountain" },
    { rank: 13, cyrillic: "пътека", latin: "pateka", phonetic: "puhtehka", englishMeaning: "trail" },
    { rank: 14, cyrillic: "змия", latin: "zmiya", phonetic: "zmeeya", englishMeaning: "snake" },
    { rank: 15, cyrillic: "овчарско куче", latin: "ovcharsko kuche", phonetic: "ovcharsko koocheh", englishMeaning: "sheep dog" },
    { rank: 16, cyrillic: "кон", latin: "kon", phonetic: "kon", englishMeaning: "horse" },
    { rank: 17, cyrillic: "връх", latin: "vrah", phonetic: "vruhkh", englishMeaning: "mountain peak" },
    { rank: 18, cyrillic: "бобиком", latin: "bobikom", phonetic: "bobeekom", englishMeaning: "bobikom hut on trail E3 Kom-Emine" },
    { rank: 19, cyrillic: "ком нова", latin: "kom nova", phonetic: "kom nova", englishMeaning: "kom hut new on trail E3 Kom-Emine" },
    { rank: 20, cyrillic: "ком стара", latin: "kom stara", phonetic: "kom stara", englishMeaning: "kom hut old on trail E3 Kom-Emine" },
    { rank: 21, cyrillic: "петрохан", latin: "petrohan", phonetic: "pehtrokhan", englishMeaning: "petrohan creative house on trail E3 Kom-Emine" },
    { rank: 22, cyrillic: "пробойница", latin: "proboynitsa", phonetic: "proboyneetsa", englishMeaning: "proboynitsa hut on trail E3 Kom-Emine" },
    { rank: 23, cyrillic: "тръстеная", latin: "trastenaya", phonetic: "truhstehnaya", englishMeaning: "trastenaya hut on trail E3 Kom-Emine" },
    { rank: 24, cyrillic: "лескова", latin: "leskova", phonetic: "lehskova", englishMeaning: "leskova hut on trail E3 Kom-Emine" },
    { rank: 25, cyrillic: "мургаш", latin: "murgash", phonetic: "moorgash", englishMeaning: "murgash hut on trail E3 Kom-Emine" },
    { rank: 26, cyrillic: "чавдар", latin: "chavdar", phonetic: "chavdar", englishMeaning: "chavdar hut on trail E3 Kom-Emine" },
    { rank: 27, cyrillic: "мургана", latin: "murgana", phonetic: "moorgana", englishMeaning: "murgana hut on trail E3 Kom-Emine" },
    { rank: 28, cyrillic: "кашана", latin: "kashana", phonetic: "kashana", englishMeaning: "kashana hut on trail E3 Kom-Emine" },
    { rank: 29, cyrillic: "свищиплаз", latin: "svishtiplaz", phonetic: "sveeshteeplaz", englishMeaning: "svishtiplaz hut on trail E3 Kom-Emine" },
    { rank: 30, cyrillic: "момина поляна", latin: "momina polyana", phonetic: "momeena polyana", englishMeaning: "momina polyana hut on trail E3 Kom-Emine" },
    { rank: 31, cyrillic: "иванина поляна", latin: "ivanina polyana", phonetic: "eevaneena polyana", englishMeaning: "ivanina polyana hut on trail E3 Kom-Emine" },
    { rank: 32, cyrillic: "бенковски", latin: "benkovski", phonetic: "behnkovskee", englishMeaning: "benkovski hut on trail E3 Kom-Emine" },
    { rank: 33, cyrillic: "вежен", latin: "vezhen", phonetic: "vehzhehn", englishMeaning: "vezhen hut on trail E3 Kom-Emine" },
    { rank: 34, cyrillic: "хижа ехо", latin: "hizha eho", phonetic: "kheezha ehkho", englishMeaning: "echo hut on trail E3 Kom-Emine" },
    { rank: 35, cyrillic: "хижа козята стена", latin: "hizha kozyata stena", phonetic: "kheezha kozyata stehna", englishMeaning: "kozya stena hut on trail E3 Kom-Emine" },
    { rank: 36, cyrillic: "заслон орлово гнездо", latin: "zaslon orlovo gnezdo", phonetic: "zaslon orlovo gnehzdo", englishMeaning: "orlovo gnezdo shelter on trail E3 Kom-Emine" },
    { rank: 37, cyrillic: "пешова мъка", latin: "peshova maka", phonetic: "pehshova muhka", englishMeaning: "peshova muka hut on trail E3 Kom-Emine" },
    { rank: 38, cyrillic: "дерменка", latin: "dermenka", phonetic: "dehrmehnka", englishMeaning: "dermenka hut on trail E3 Kom-Emine" },
    { rank: 39, cyrillic: "добрила", latin: "dobrila", phonetic: "dobreela", englishMeaning: "dobrila hut on trail E3 Kom-Emine" },
    { rank: 40, cyrillic: "заслон амбарица", latin: "zaslon ambaritsa", phonetic: "zaslon ambareetsa", englishMeaning: "ambaritsa shelter on trail E3 Kom-Emine" },
    { rank: 41, cyrillic: "хижа васил левски", latin: "hizha vasil levski", phonetic: "kheezha vaseel lehvskee", englishMeaning: "vasil levski hut on trail E3 Kom-Emine" },
    { rank: 42, cyrillic: "заслон ботев", latin: "zaslon botev", phonetic: "zaslon botehv", englishMeaning: "botev shelter on trail E3 Kom-Emine" },
    { rank: 43, cyrillic: "заслон маринка", latin: "zaslon marinka", phonetic: "zaslon mareenka", englishMeaning: "marinka shelter on trail E3 Kom-Emine" },
    { rank: 44, cyrillic: "заслон михайлов", latin: "zaslon mihaylov", phonetic: "zaslon meekhaylov", englishMeaning: "mihaylov shelter on trail E3 Kom-Emine" },
    { rank: 45, cyrillic: "тъжа", latin: "tazha", phonetic: "tuhzha", englishMeaning: "tazha hut on trail E3 Kom-Emine" },
    { rank: 46, cyrillic: "мандрата", latin: "mandrata", phonetic: "mandrata", englishMeaning: "mandrata hut on trail E3 Kom-Emine" },
    { rank: 47, cyrillic: "мазалат", latin: "mazalat", phonetic: "mazalat", englishMeaning: "mazalat hut on trail E3 Kom-Emine" },
    { rank: 48, cyrillic: "партизанска песен", latin: "partizanska pesen", phonetic: "parteezanska pehsehn", englishMeaning: "partizanska pesen hut on trail E3 Kom-Emine" },
    { rank: 49, cyrillic: "узана", latin: "uzana", phonetic: "oozana", englishMeaning: "uzana hut on trail E3 Kom-Emine" },
    { rank: 50, cyrillic: "бузлуджа стара", latin: "buzludzha stara", phonetic: "boozloodzha stara", englishMeaning: "buzludzha hut old on trail E3 Kom-Emine" },
    { rank: 51, cyrillic: "бузлуджа нова", latin: "buzludzha nova", phonetic: "boozloodzha nova", englishMeaning: "buzludzha hut new on trail E3 Kom-Emine" },
    { rank: 52, cyrillic: "българка", latin: "balgarka", phonetic: "buhlgarka", englishMeaning: "balgarka hut on trail E3 Kom-Emine" },
    { rank: 53, cyrillic: "планинец", latin: "planinets", phonetic: "planeenehts", englishMeaning: "planinets hut on trail E3 Kom-Emine" },
    { rank: 54, cyrillic: "кръстец", latin: "krastets", phonetic: "kruhstehts", englishMeaning: "krastets hut on trail E3 Kom-Emine" },
    { rank: 55, cyrillic: "грамадлива", latin: "gramadliva", phonetic: "gramadleeva", englishMeaning: "gramadliva hut on trail E3 Kom-Emine" },
    { rank: 56, cyrillic: "химик", latin: "himik", phonetic: "kheemeek", englishMeaning: "himik hut on trail E3 Kom-Emine" },
    { rank: 57, cyrillic: "предела", latin: "predela", phonetic: "prehdehla", englishMeaning: "predela hut on trail E3 Kom-Emine" },
    { rank: 58, cyrillic: "заслон караиваново хорище", latin: "zaslon karaivanovo horishte", phonetic: "zaslon karaeevanovo khoreeshteh", englishMeaning: "karaivanovo horishte shelter on trail E3 Kom-Emine" },
    { rank: 59, cyrillic: "буковец", latin: "bukovets", phonetic: "bookovehts", englishMeaning: "bukovets hut on trail E3 Kom-Emine" },
    { rank: 60, cyrillic: "чумерна", latin: "chumerna", phonetic: "choomehrna", englishMeaning: "chumerna hut on trail E3 Kom-Emine" },
    { rank: 61, cyrillic: "заслон вратник", latin: "zaslon vratnik", phonetic: "zaslon vratneek", englishMeaning: "vratnik shelter on trail E3 Kom-Emine" },
    { rank: 62, cyrillic: "върбишки проход", latin: "varbishki prohod", phonetic: "vuhrbeeshkee prokhod", englishMeaning: "varbishki pass hut on trail E3 Kom-Emine" },
    { rank: 63, cyrillic: "заслон хазим горския", latin: "zaslon hazim gorskiya", phonetic: "zaslon khazeem gorskeeya", englishMeaning: "hazim gorskiya shelter on trail E3 Kom-Emine" },
    { rank: 64, cyrillic: "хижа топчийско", latin: "hizha topchiysko", phonetic: "kheezha topcheeysko", englishMeaning: "topchiysko hut on trail E3 Kom-Emine" },
    { rank: 65, cyrillic: "козичино", latin: "kozichino", phonetic: "kozeecheeno", englishMeaning: "kozichino tourist dormitory on trail E3 Kom-Emine" },
    { rank: 66, cyrillic: "емона", latin: "emona", phonetic: "ehmona", englishMeaning: "emona area near cape emine" },
    { rank: 67, cyrillic: "фенерче", latin: "fenerche", phonetic: "fehnehrcheh", englishMeaning: "flashlight" },
    { rank: 68, cyrillic: "термобельо", latin: "termobelyo", phonetic: "tehrmobehlyo", englishMeaning: "thermal underwear" },
    { rank: 69, cyrillic: "южен склон", latin: "yuzhen sklon", phonetic: "yuzhehn sklon", englishMeaning: "southern slope" },
    { rank: 70, cyrillic: "пещера", latin: "peshtera", phonetic: "pehshtehra", englishMeaning: "cave" },
    { rank: 71, cyrillic: "нощувка", latin: "noshtuvka", phonetic: "noshtoovka", englishMeaning: "overnight stay" },
    { rank: 72, cyrillic: "филтър за вода", latin: "filtar za voda", phonetic: "feeltuhr za voda", englishMeaning: "water filter" },
    { rank: 73, cyrillic: "слънцезащита", latin: "slantsezashtita", phonetic: "sluhntsehzashteeta", englishMeaning: "sun protection" },
    { rank: 74, cyrillic: "каньон", latin: "kanyon", phonetic: "kanyon", englishMeaning: "canyon" },
    { rank: 75, cyrillic: "южен вятър", latin: "yuzhen vyatar", phonetic: "yuzhehn vyatuhr", englishMeaning: "southern wind" },
    { rank: 76, cyrillic: "шофьор", latin: "shofyor", phonetic: "shofyor", englishMeaning: "driver" },
    { rank: 77, cyrillic: "чайник", latin: "chaynik", phonetic: "chayneek", englishMeaning: "kettle" },
    { rank: 78, cyrillic: "южен маршрут", latin: "yuzhen marshrut", phonetic: "yuzhehn marshroot", englishMeaning: "southern route" },
    { rank: 79, cyrillic: "югоизточен склон", latin: "yugoiztochen sklon", phonetic: "yugoeeztochehn sklon", englishMeaning: "southeastern slope" },
    { rank: 80, cyrillic: "термофолио", latin: "termofolio", phonetic: "tehrmofoleeo", englishMeaning: "emergency thermal blanket" },
    { rank: 81, cyrillic: "флисово яке", latin: "flisovo yake", phonetic: "fleesovo yakeh", englishMeaning: "fleece jacket" },
    { rank: 82, cyrillic: "каньонинг", latin: "kanyoning", phonetic: "kanyoneeng", englishMeaning: "canyoning" },
    { rank: 83, cyrillic: "планински водач", latin: "planinski vodach", phonetic: "planeenskee vodach", englishMeaning: "mountain guide" },
    { rank: 84, cyrillic: "чешма", latin: "cheshma", phonetic: "chehshma", englishMeaning: "water source" },
    { rank: 85, cyrillic: "искам нощувка", latin: "iskam noshtuvka", phonetic: "eeskam noshtoovka", englishMeaning: "I want a place to sleep" },
    { rank: 86, cyrillic: "стръмно", latin: "stramno", phonetic: "'struhm-no", englishMeaning: "steep, steeply" },
    { rank: 87, cyrillic: "обрасло", latin: "obraslo", phonetic: "obraslo", englishMeaning: "overgrown" },
    { rank: 88, cyrillic: "въже", latin: "vazhe", phonetic: "va-zhe", englishMeaning: "rope or wire (to support dangerous spot)" }
  ];

  const ALPHABET_WORD_SOURCE = [
    { rank: 1, cyrillic: "а", latin: "a", phonetic: "a", englishMeaning: "Cyrillic letter а" },
    { rank: 2, cyrillic: "б", latin: "b", phonetic: "b", englishMeaning: "Cyrillic letter б" },
    { rank: 3, cyrillic: "в", latin: "v", phonetic: "v", englishMeaning: "Cyrillic letter в" },
    { rank: 4, cyrillic: "г", latin: "g", phonetic: "g", englishMeaning: "Cyrillic letter г" },
    { rank: 5, cyrillic: "д", latin: "d", phonetic: "d", englishMeaning: "Cyrillic letter д" },
    { rank: 6, cyrillic: "е", latin: "e", phonetic: "eh", englishMeaning: "Cyrillic letter е" },
    { rank: 7, cyrillic: "ж", latin: "zh", phonetic: "zh", englishMeaning: "Cyrillic letter ж" },
    { rank: 8, cyrillic: "з", latin: "z", phonetic: "z", englishMeaning: "Cyrillic letter з" },
    { rank: 9, cyrillic: "и", latin: "i", phonetic: "ee", englishMeaning: "Cyrillic letter и" },
    { rank: 10, cyrillic: "й", latin: "y", phonetic: "y", englishMeaning: "Cyrillic letter й" },
    { rank: 11, cyrillic: "к", latin: "k", phonetic: "k", englishMeaning: "Cyrillic letter к" },
    { rank: 12, cyrillic: "л", latin: "l", phonetic: "l", englishMeaning: "Cyrillic letter л" },
    { rank: 13, cyrillic: "м", latin: "m", phonetic: "m", englishMeaning: "Cyrillic letter м" },
    { rank: 14, cyrillic: "н", latin: "n", phonetic: "n", englishMeaning: "Cyrillic letter н" },
    { rank: 15, cyrillic: "о", latin: "o", phonetic: "o", englishMeaning: "Cyrillic letter о" },
    { rank: 16, cyrillic: "п", latin: "p", phonetic: "p", englishMeaning: "Cyrillic letter п" },
    { rank: 17, cyrillic: "р", latin: "r", phonetic: "r", englishMeaning: "Cyrillic letter р" },
    { rank: 18, cyrillic: "с", latin: "s", phonetic: "s", englishMeaning: "Cyrillic letter с" },
    { rank: 19, cyrillic: "т", latin: "t", phonetic: "t", englishMeaning: "Cyrillic letter т" },
    { rank: 20, cyrillic: "у", latin: "u", phonetic: "oo", englishMeaning: "Cyrillic letter у" },
    { rank: 21, cyrillic: "ф", latin: "f", phonetic: "f", englishMeaning: "Cyrillic letter ф" },
    { rank: 22, cyrillic: "х", latin: "h", phonetic: "kh", englishMeaning: "Cyrillic letter х" },
    { rank: 23, cyrillic: "ц", latin: "ts", phonetic: "ts", englishMeaning: "Cyrillic letter ц" },
    { rank: 24, cyrillic: "ч", latin: "ch", phonetic: "ch", englishMeaning: "Cyrillic letter ч" },
    { rank: 25, cyrillic: "ш", latin: "sh", phonetic: "sh", englishMeaning: "Cyrillic letter ш" },
    { rank: 26, cyrillic: "щ", latin: "sht", phonetic: "sht", englishMeaning: "Cyrillic letter щ" },
    { rank: 27, cyrillic: "ъ", latin: "a", phonetic: "uh", englishMeaning: "Cyrillic letter ъ" },
    { rank: 28, cyrillic: "ь", latin: "y", phonetic: "y", englishMeaning: "Cyrillic letter ь" },
    { rank: 29, cyrillic: "ю", latin: "yu", phonetic: "yu", englishMeaning: "Cyrillic letter ю" },
    { rank: 30, cyrillic: "я", latin: "ya", phonetic: "ya", englishMeaning: "Cyrillic letter я" }
  ];

  window.CYRILLIC_TRAINER_DATA = {
    source: {
      wordFrequency: "https://github.com/hermitdave/FrequencyWords/blob/master/content/2018/bg/bg_50k.txt",
      hikingHuts: "https://kom-emine.bg/huts-all-en/?lang=en",
      note: "Common ranks 247-250 replace less frequent source words to cover all lowercase Bulgarian Cyrillic letters."
    },
    letterTransliterations: LETTER_TRANSLITERATIONS,
    letterOptions: LETTER_OPTIONS,
    wordSource: WORD_SOURCE,
    datasets: [
      { id: "1", label: "top 250 words", wordSource: WORD_SOURCE },
      { id: "2", label: "Hiking E3 Kom-Emine words", wordSource: HIKING_WORD_SOURCE },
      { id: "3", label: "alphabet letters", wordSource: ALPHABET_WORD_SOURCE }
    ]
  };
}());
