(function () {
  "use strict";

  const LETTER_TRANSLITERATIONS = [
    { cyrillic: "а", latin: "a", mustAsk: ["o", "e", "u"] },
    { cyrillic: "б", latin: "b", mustAsk: ["v", "d", "g"] },
    { cyrillic: "в", latin: "v", mustAsk: ["b", "w", "f"] },
    { cyrillic: "г", latin: "g", mustAsk: ["r", "h", "k"] },
    { cyrillic: "д", latin: "d", mustAsk: ["g", "a", "t", "l"] },
    { cyrillic: "е", latin: "e", mustAsk: ["i", "y", "a"] },
    { cyrillic: "ж", latin: "zh", mustAsk: ["sh", "ch", "z", "j"] },
    { cyrillic: "з", latin: "z", mustAsk: ["s", "e", "zh"] },
    { cyrillic: "и", latin: "i", mustAsk: ["n", "u", "y"] },
    { cyrillic: "й", latin: "y", mustAsk: ["i", "u", "j"] },
    { cyrillic: "к", latin: "k", mustAsk: ["x", "h", "q"] },
    { cyrillic: "л", latin: "l", mustAsk: ["r", "m", "n"] },
    { cyrillic: "м", latin: "m", mustAsk: ["n", "h", "l"] },
    { cyrillic: "н", latin: "n", mustAsk: ["h", "m", "u"] },
    { cyrillic: "о", latin: "o", mustAsk: ["a", "e", "u"] },
    { cyrillic: "п", latin: "p", mustAsk: ["n", "u", "r", "b"] },
    { cyrillic: "р", latin: "r", mustAsk: ["p", "b", "l"] },
    { cyrillic: "с", latin: "s", mustAsk: ["c", "z", "k"] },
    { cyrillic: "т", latin: "t", mustAsk: ["m", "d", "n"] },
    { cyrillic: "у", latin: "u", mustAsk: ["y", "v", "w"] },
    { cyrillic: "ф", latin: "f", mustAsk: ["o", "p", "v"] },
    { cyrillic: "х", latin: "h", mustAsk: ["x", "k", "ch"] },
    { cyrillic: "ц", latin: "ts", mustAsk: ["c", "s", "ch"] },
    { cyrillic: "ч", latin: "ch", mustAsk: ["sh", "ts", "c"] },
    { cyrillic: "ш", latin: "sh", mustAsk: ["ch", "sht", "s"] },
    { cyrillic: "щ", latin: "sht", mustAsk: ["sh", "ch", "ts"] },
    { cyrillic: "ъ", latin: "a", mustAsk: ["u", "y", "o"] },
    { cyrillic: "ь", latin: "y", mustAsk: ["b", "i", "u"] },
    { cyrillic: "ю", latin: "yu", mustAsk: ["u", "ya", "y"] },
    { cyrillic: "я", latin: "ya", mustAsk: ["r", "a", "yu"] },
    { cyrillic: "А", latin: "A", mustAsk: ["O", "E", "U"] },
    { cyrillic: "Б", latin: "B", mustAsk: ["V", "D", "G"] },
    { cyrillic: "В", latin: "V", mustAsk: ["B", "W", "F"] },
    { cyrillic: "Г", latin: "G", mustAsk: ["L", "T", "K"] },
    { cyrillic: "Д", latin: "D", mustAsk: ["A", "L", "G", "T"] },
    { cyrillic: "Е", latin: "E", mustAsk: ["I", "Y", "A"] },
    { cyrillic: "Ж", latin: "ZH", mustAsk: ["SH", "CH", "Z", "J"] },
    { cyrillic: "З", latin: "Z", mustAsk: ["S", "E", "ZH"] },
    { cyrillic: "И", latin: "I", mustAsk: ["N", "U", "Y"] },
    { cyrillic: "Й", latin: "Y", mustAsk: ["I", "N", "U"] },
    { cyrillic: "К", latin: "K", mustAsk: ["X", "H", "Q"] },
    { cyrillic: "Л", latin: "L", mustAsk: ["A", "M", "N"] },
    { cyrillic: "М", latin: "M", mustAsk: ["N", "H", "L"] },
    { cyrillic: "Н", latin: "N", mustAsk: ["H", "M", "U"] },
    { cyrillic: "О", latin: "O", mustAsk: ["A", "E", "U"] },
    { cyrillic: "П", latin: "P", mustAsk: ["N", "U", "R", "B"] },
    { cyrillic: "Р", latin: "R", mustAsk: ["P", "B", "L"] },
    { cyrillic: "С", latin: "S", mustAsk: ["C", "Z", "K"] },
    { cyrillic: "Т", latin: "T", mustAsk: ["M", "D", "N"] },
    { cyrillic: "У", latin: "U", mustAsk: ["Y", "V", "W"] },
    { cyrillic: "Ф", latin: "F", mustAsk: ["O", "P", "V"] },
    { cyrillic: "Х", latin: "H", mustAsk: ["X", "K", "CH"] },
    { cyrillic: "Ц", latin: "TS", mustAsk: ["C", "S", "CH", "U"] },
    { cyrillic: "Ч", latin: "CH", mustAsk: ["SH", "TS", "C"] },
    { cyrillic: "Ш", latin: "SH", mustAsk: ["W", "CH", "SHT", "S"] },
    { cyrillic: "Щ", latin: "SHT", mustAsk: ["W", "SH", "CH", "TS"] },
    { cyrillic: "Ъ", latin: "A", mustAsk: ["B", "U", "Y", "O"] },
    { cyrillic: "Ь", latin: "Y", mustAsk: ["B", "I", "U"] },
    { cyrillic: "Ю", latin: "YU", mustAsk: ["U", "YA", "Y", "O"] },
    { cyrillic: "Я", latin: "YA", mustAsk: ["R", "A", "YU"] }
  ];

  const LETTER_OPTIONS = [
    "a",
    "b",
    "c",
    "ch",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "p",
    "q",
    "r",
    "s",
    "sh",
    "sht",
    "t",
    "ts",
    "u",
    "v",
    "w",
    "x",
    "y",
    "ya",
    "yu",
    "z",
    "zh"
  ];

  const WORD_SOURCE = [
    { rank: 1, cyrillic: "да", latin: "da", englishmeaning: "yes" },
    { rank: 2, cyrillic: "е", latin: "e", englishmeaning: "is" },
    { rank: 3, cyrillic: "не", latin: "ne", englishmeaning: "no, not" },
    { rank: 4, cyrillic: "се", latin: "se", englishmeaning: "self, reflexive particle" },
    { rank: 5, cyrillic: "и", latin: "i", englishmeaning: "and" },
    { rank: 6, cyrillic: "на", latin: "na", englishmeaning: "of, on, to" },
    { rank: 7, cyrillic: "си", latin: "si", englishmeaning: "oneself, own" },
    { rank: 8, cyrillic: "за", latin: "za", englishmeaning: "for, about" },
    { rank: 9, cyrillic: "ще", latin: "shte", englishmeaning: "will" },
    { rank: 10, cyrillic: "че", latin: "che", englishmeaning: "that" },
    { rank: 11, cyrillic: "това", latin: "tova", englishmeaning: "this, that" },
    { rank: 12, cyrillic: "ли", latin: "li", englishmeaning: "question particle" },
    { rank: 13, cyrillic: "в", latin: "v", englishmeaning: "in" },
    { rank: 14, cyrillic: "ти", latin: "ti", englishmeaning: "you" },
    { rank: 15, cyrillic: "от", latin: "ot", englishmeaning: "from, by" },
    { rank: 16, cyrillic: "ми", latin: "mi", englishmeaning: "my, to me" },
    { rank: 17, cyrillic: "с", latin: "s", englishmeaning: "with" },
    { rank: 18, cyrillic: "какво", latin: "kakvo", englishmeaning: "what" },
    { rank: 19, cyrillic: "го", latin: "go", englishmeaning: "him, it" },
    { rank: 20, cyrillic: "съм", latin: "sam", englishmeaning: "I am" },
    { rank: 21, cyrillic: "но", latin: "no", englishmeaning: "but" },
    { rank: 22, cyrillic: "аз", latin: "az", englishmeaning: "I" },
    { rank: 23, cyrillic: "те", latin: "te", englishmeaning: "they, them" },
    { rank: 24, cyrillic: "трябва", latin: "tryabva", englishmeaning: "must, should" },
    { rank: 25, cyrillic: "добре", latin: "dobre", englishmeaning: "well, good" },
    { rank: 26, cyrillic: "ме", latin: "me", englishmeaning: "me" },
    { rank: 27, cyrillic: "са", latin: "sa", englishmeaning: "are" },
    { rank: 28, cyrillic: "няма", latin: "nyama", englishmeaning: "there is no, will not" },
    { rank: 29, cyrillic: "може", latin: "mozhe", englishmeaning: "can, may" },
    { rank: 30, cyrillic: "ако", latin: "ako", englishmeaning: "if" },
    { rank: 31, cyrillic: "тук", latin: "tuk", englishmeaning: "here" },
    { rank: 32, cyrillic: "така", latin: "taka", englishmeaning: "so, like this" },
    { rank: 33, cyrillic: "а", latin: "a", englishmeaning: "and, but" },
    { rank: 34, cyrillic: "ви", latin: "vi", englishmeaning: "you, your" },
    { rank: 35, cyrillic: "като", latin: "kato", englishmeaning: "as, like" },
    { rank: 36, cyrillic: "много", latin: "mnogo", englishmeaning: "much, many, very" },
    { rank: 37, cyrillic: "той", latin: "toy", englishmeaning: "he" },
    { rank: 38, cyrillic: "по", latin: "po", englishmeaning: "along, by, more" },
    { rank: 39, cyrillic: "има", latin: "ima", englishmeaning: "there is, has" },
    { rank: 40, cyrillic: "беше", latin: "beshe", englishmeaning: "was" },
    { rank: 41, cyrillic: "нещо", latin: "neshto", englishmeaning: "something" },
    { rank: 42, cyrillic: "му", latin: "mu", englishmeaning: "his, to him" },
    { rank: 43, cyrillic: "как", latin: "kak", englishmeaning: "how" },
    { rank: 44, cyrillic: "защо", latin: "zashto", englishmeaning: "why" },
    { rank: 45, cyrillic: "ни", latin: "ni", englishmeaning: "us, our" },
    { rank: 46, cyrillic: "я", latin: "ya", englishmeaning: "her, it" },
    { rank: 47, cyrillic: "знам", latin: "znam", englishmeaning: "I know" },
    { rank: 48, cyrillic: "само", latin: "samo", englishmeaning: "only" },
    { rank: 49, cyrillic: "всичко", latin: "vsichko", englishmeaning: "everything" },
    { rank: 50, cyrillic: "мен", latin: "men", englishmeaning: "me" },
    { rank: 51, cyrillic: "сега", latin: "sega", englishmeaning: "now" },
    { rank: 52, cyrillic: "теб", latin: "teb", englishmeaning: "you" },
    { rank: 53, cyrillic: "тя", latin: "tya", englishmeaning: "she" },
    { rank: 54, cyrillic: "което", latin: "koeto", englishmeaning: "which, that" },
    { rank: 55, cyrillic: "искам", latin: "iskam", englishmeaning: "I want" },
    { rank: 56, cyrillic: "мога", latin: "moga", englishmeaning: "I can" },
    { rank: 57, cyrillic: "още", latin: "oshte", englishmeaning: "more, still, yet" },
    { rank: 58, cyrillic: "когато", latin: "kogato", englishmeaning: "when" },
    { rank: 59, cyrillic: "до", latin: "do", englishmeaning: "to, until" },
    { rank: 60, cyrillic: "ги", latin: "gi", englishmeaning: "them" },
    { rank: 61, cyrillic: "този", latin: "tozi", englishmeaning: "this" },
    { rank: 62, cyrillic: "просто", latin: "prosto", englishmeaning: "simply, just" },
    { rank: 63, cyrillic: "сте", latin: "ste", englishmeaning: "you are" },
    { rank: 64, cyrillic: "или", latin: "ili", englishmeaning: "or" },
    { rank: 65, cyrillic: "къде", latin: "kade", englishmeaning: "where" },
    { rank: 66, cyrillic: "би", latin: "bi", englishmeaning: "would" },
    { rank: 67, cyrillic: "тази", latin: "tazi", englishmeaning: "this" },
    { rank: 68, cyrillic: "всички", latin: "vsichki", englishmeaning: "all, everyone" },
    { rank: 69, cyrillic: "благодаря", latin: "blagodarya", englishmeaning: "thank you" },
    { rank: 70, cyrillic: "нали", latin: "nali", englishmeaning: "right, is it not" },
    { rank: 71, cyrillic: "сме", latin: "sme", englishmeaning: "we are" },
    { rank: 72, cyrillic: "нищо", latin: "nishto", englishmeaning: "nothing" },
    { rank: 73, cyrillic: "толкова", latin: "tolkova", englishmeaning: "so much" },
    { rank: 74, cyrillic: "знаеш", latin: "znaesh", englishmeaning: "you know" },
    { rank: 75, cyrillic: "един", latin: "edin", englishmeaning: "one, a" },
    { rank: 76, cyrillic: "защото", latin: "zashtoto", englishmeaning: "because" },
    { rank: 77, cyrillic: "след", latin: "sled", englishmeaning: "after" },
    { rank: 78, cyrillic: "там", latin: "tam", englishmeaning: "there" },
    { rank: 79, cyrillic: "време", latin: "vreme", englishmeaning: "time, weather" },
    { rank: 80, cyrillic: "който", latin: "koyto", englishmeaning: "who, which" },
    { rank: 81, cyrillic: "искаш", latin: "iskash", englishmeaning: "you want" },
    { rank: 82, cyrillic: "мисля", latin: "mislya", englishmeaning: "I think" },
    { rank: 83, cyrillic: "кой", latin: "koy", englishmeaning: "who" },
    { rank: 84, cyrillic: "малко", latin: "malko", englishmeaning: "little, a little" },
    { rank: 85, cyrillic: "имам", latin: "imam", englishmeaning: "I have" },
    { rank: 86, cyrillic: "преди", latin: "predi", englishmeaning: "before" },
    { rank: 87, cyrillic: "хайде", latin: "hayde", englishmeaning: "come on" },
    { rank: 88, cyrillic: "вече", latin: "veche", englishmeaning: "already" },
    { rank: 89, cyrillic: "тези", latin: "tezi", englishmeaning: "these" },
    { rank: 90, cyrillic: "моля", latin: "molya", englishmeaning: "please" },
    { rank: 91, cyrillic: "о", latin: "o", englishmeaning: "oh" },
    { rank: 92, cyrillic: "някой", latin: "nyakoy", englishmeaning: "someone" },
    { rank: 93, cyrillic: "каза", latin: "kaza", englishmeaning: "said" },
    { rank: 94, cyrillic: "него", latin: "nego", englishmeaning: "him" },
    { rank: 95, cyrillic: "наистина", latin: "naistina", englishmeaning: "really, truly" },
    { rank: 96, cyrillic: "ние", latin: "nie", englishmeaning: "we" },
    { rank: 97, cyrillic: "вие", latin: "vie", englishmeaning: "you" },
    { rank: 98, cyrillic: "които", latin: "koito", englishmeaning: "who, which" },
    { rank: 99, cyrillic: "й", latin: "y", englishmeaning: "her, to her" },
    { rank: 100, cyrillic: "повече", latin: "poveche", englishmeaning: "more" },
    { rank: 101, cyrillic: "съжалявам", latin: "sazhalyavam", englishmeaning: "I am sorry" },
    { rank: 102, cyrillic: "тогава", latin: "togava", englishmeaning: "then" },
    { rank: 103, cyrillic: "точно", latin: "tochno", englishmeaning: "exactly" },
    { rank: 104, cyrillic: "става", latin: "stava", englishmeaning: "happens, becomes" },
    { rank: 105, cyrillic: "все", latin: "vse", englishmeaning: "still, always" },
    { rank: 106, cyrillic: "можеш", latin: "mozhesh", englishmeaning: "you can" },
    { rank: 107, cyrillic: "една", latin: "edna", englishmeaning: "one, a" },
    { rank: 108, cyrillic: "имаш", latin: "imash", englishmeaning: "you have" },
    { rank: 109, cyrillic: "към", latin: "kam", englishmeaning: "toward" },
    { rank: 110, cyrillic: "без", latin: "bez", englishmeaning: "without" },
    { rank: 111, cyrillic: "колко", latin: "kolko", englishmeaning: "how much, how many" },
    { rank: 112, cyrillic: "кажа", latin: "kazha", englishmeaning: "I say, I will say" },
    { rank: 113, cyrillic: "никога", latin: "nikoga", englishmeaning: "never" },
    { rank: 114, cyrillic: "при", latin: "pri", englishmeaning: "at, near, with" },
    { rank: 115, cyrillic: "човек", latin: "chovek", englishmeaning: "person, man" },
    { rank: 116, cyrillic: "работа", latin: "rabota", englishmeaning: "work, job" },
    { rank: 117, cyrillic: "им", latin: "im", englishmeaning: "them, their" },
    { rank: 118, cyrillic: "ден", latin: "den", englishmeaning: "day" },
    { rank: 119, cyrillic: "едно", latin: "edno", englishmeaning: "one, a" },
    { rank: 120, cyrillic: "бях", latin: "byah", englishmeaning: "I was" },
    { rank: 121, cyrillic: "бъде", latin: "bade", englishmeaning: "be, become" },
    { rank: 122, cyrillic: "през", latin: "prez", englishmeaning: "through, during" },
    { rank: 123, cyrillic: "ето", latin: "eto", englishmeaning: "here is" },
    { rank: 124, cyrillic: "значи", latin: "znachi", englishmeaning: "means, so" },
    { rank: 125, cyrillic: "със", latin: "sas", englishmeaning: "with" },
    { rank: 126, cyrillic: "дори", latin: "dori", englishmeaning: "even" },
    { rank: 127, cyrillic: "хора", latin: "hora", englishmeaning: "people" },
    { rank: 128, cyrillic: "път", latin: "pat", englishmeaning: "road, time" },
    { rank: 129, cyrillic: "както", latin: "kakto", englishmeaning: "as, like" },
    { rank: 130, cyrillic: "нас", latin: "nas", englishmeaning: "us" },
    { rank: 131, cyrillic: "години", latin: "godini", englishmeaning: "years" },
    { rank: 132, cyrillic: "бил", latin: "bil", englishmeaning: "was, has been" },
    { rank: 133, cyrillic: "баща", latin: "bashta", englishmeaning: "father" },
    { rank: 134, cyrillic: "правиш", latin: "pravish", englishmeaning: "you do, you make" },
    { rank: 135, cyrillic: "която", latin: "koyato", englishmeaning: "who, which" },
    { rank: 136, cyrillic: "разбира", latin: "razbira", englishmeaning: "understands" },
    { rank: 137, cyrillic: "също", latin: "sashto", englishmeaning: "also" },
    { rank: 138, cyrillic: "мислиш", latin: "mislish", englishmeaning: "you think" },
    { rank: 139, cyrillic: "вас", latin: "vas", englishmeaning: "you" },
    { rank: 140, cyrillic: "ами", latin: "ami", englishmeaning: "well" },
    { rank: 141, cyrillic: "нея", latin: "neya", englishmeaning: "her" },
    { rank: 142, cyrillic: "направи", latin: "napravi", englishmeaning: "made, did" },
    { rank: 143, cyrillic: "винаги", latin: "vinagi", englishmeaning: "always" },
    { rank: 144, cyrillic: "докато", latin: "dokato", englishmeaning: "while, until" },
    { rank: 145, cyrillic: "имаме", latin: "imame", englishmeaning: "we have" },
    { rank: 146, cyrillic: "виж", latin: "vizh", englishmeaning: "look, see" },
    { rank: 147, cyrillic: "всеки", latin: "vseki", englishmeaning: "every, everyone" },
    { rank: 148, cyrillic: "иска", latin: "iska", englishmeaning: "wants" },
    { rank: 149, cyrillic: "майка", latin: "mayka", englishmeaning: "mother" },
    { rank: 150, cyrillic: "казах", latin: "kazah", englishmeaning: "I said" },
    { rank: 151, cyrillic: "нека", latin: "neka", englishmeaning: "let" },
    { rank: 152, cyrillic: "хората", latin: "horata", englishmeaning: "the people" },
    { rank: 153, cyrillic: "хей", latin: "hey", englishmeaning: "hey" },
    { rank: 154, cyrillic: "жена", latin: "zhena", englishmeaning: "woman, wife" },
    { rank: 155, cyrillic: "видя", latin: "vidya", englishmeaning: "saw, see" },
    { rank: 156, cyrillic: "дали", latin: "dali", englishmeaning: "whether" },
    { rank: 157, cyrillic: "във", latin: "vav", englishmeaning: "in" },
    { rank: 158, cyrillic: "никой", latin: "nikoy", englishmeaning: "nobody" },
    { rank: 159, cyrillic: "пак", latin: "pak", englishmeaning: "again" },
    { rank: 160, cyrillic: "тях", latin: "tyah", englishmeaning: "them" },
    { rank: 161, cyrillic: "направя", latin: "napravya", englishmeaning: "I make, I do" },
    { rank: 162, cyrillic: "неща", latin: "neshta", englishmeaning: "things" },
    { rank: 163, cyrillic: "кажи", latin: "kazhi", englishmeaning: "say, tell" },
    { rank: 164, cyrillic: "място", latin: "myasto", englishmeaning: "place" },
    { rank: 165, cyrillic: "заради", latin: "zaradi", englishmeaning: "because of" },
    { rank: 166, cyrillic: "прави", latin: "pravi", englishmeaning: "does, makes" },
    { rank: 167, cyrillic: "сър", latin: "sar", englishmeaning: "sir" },
    { rank: 168, cyrillic: "можем", latin: "mozhem", englishmeaning: "we can" },
    { rank: 169, cyrillic: "дяволите", latin: "dyavolite", englishmeaning: "the devils, damn" },
    { rank: 170, cyrillic: "изглежда", latin: "izglezhda", englishmeaning: "seems, looks" },
    { rank: 171, cyrillic: "днес", latin: "dnes", englishmeaning: "today" },
    { rank: 172, cyrillic: "кажеш", latin: "kazhesh", englishmeaning: "you say, you tell" },
    { rank: 173, cyrillic: "живота", latin: "zhivota", englishmeaning: "the life" },
    { rank: 174, cyrillic: "трябваше", latin: "tryabvashe", englishmeaning: "had to, should have" },
    { rank: 175, cyrillic: "отново", latin: "otnovo", englishmeaning: "again" },
    { rank: 176, cyrillic: "татко", latin: "tatko", englishmeaning: "dad" },
    { rank: 177, cyrillic: "няколко", latin: "nyakolko", englishmeaning: "several" },
    { rank: 178, cyrillic: "наред", latin: "nared", englishmeaning: "in order, for" },
    { rank: 179, cyrillic: "боже", latin: "bozhe", englishmeaning: "God, oh God" },
    { rank: 180, cyrillic: "друг", latin: "drug", englishmeaning: "other, another" },
    { rank: 181, cyrillic: "здравей", latin: "zdravey", englishmeaning: "hello" },
    { rank: 182, cyrillic: "затова", latin: "zatova", englishmeaning: "therefore, that is why" },
    { rank: 183, cyrillic: "бих", latin: "bih", englishmeaning: "would" },
    { rank: 184, cyrillic: "доста", latin: "dosta", englishmeaning: "quite, enough" },
    { rank: 185, cyrillic: "обичам", latin: "obicham", englishmeaning: "I love" },
    { rank: 186, cyrillic: "пари", latin: "pari", englishmeaning: "money" },
    { rank: 187, cyrillic: "знае", latin: "znae", englishmeaning: "knows" },
    { rank: 188, cyrillic: "начин", latin: "nachin", englishmeaning: "way" },
    { rank: 189, cyrillic: "моя", latin: "moya", englishmeaning: "my" },
    { rank: 190, cyrillic: "мислех", latin: "misleh", englishmeaning: "I thought" },
    { rank: 191, cyrillic: "нужда", latin: "nuzhda", englishmeaning: "need" },
    { rank: 192, cyrillic: "сам", latin: "sam", englishmeaning: "alone, by myself" },
    { rank: 193, cyrillic: "две", latin: "dve", englishmeaning: "two" },
    { rank: 194, cyrillic: "дойде", latin: "doyde", englishmeaning: "came" },
    { rank: 195, cyrillic: "заедно", latin: "zaedno", englishmeaning: "together" },
    { rank: 196, cyrillic: "добър", latin: "dobar", englishmeaning: "good" },
    { rank: 197, cyrillic: "ела", latin: "ela", englishmeaning: "come" },
    { rank: 198, cyrillic: "нямам", latin: "nyamam", englishmeaning: "I do not have" },
    { rank: 199, cyrillic: "приятел", latin: "priyatel", englishmeaning: "friend" },
    { rank: 200, cyrillic: "после", latin: "posle", englishmeaning: "afterwards, later" },
    { rank: 201, cyrillic: "видим", latin: "vidim", englishmeaning: "we see, visible" },
    { rank: 202, cyrillic: "правя", latin: "pravya", englishmeaning: "I do, I make" },
    { rank: 203, cyrillic: "вечер", latin: "vecher", englishmeaning: "evening" },
    { rank: 204, cyrillic: "достатъчно", latin: "dostatachno", englishmeaning: "enough" },
    { rank: 205, cyrillic: "всъщност", latin: "vsashtnost", englishmeaning: "actually" },
    { rank: 206, cyrillic: "исках", latin: "iskah", englishmeaning: "I wanted" },
    { rank: 207, cyrillic: "проблем", latin: "problem", englishmeaning: "problem" },
    { rank: 208, cyrillic: "живот", latin: "zhivot", englishmeaning: "life" },
    { rank: 209, cyrillic: "нещата", latin: "neshtata", englishmeaning: "the things" },
    { rank: 210, cyrillic: "под", latin: "pod", englishmeaning: "under" },
    { rank: 211, cyrillic: "каквото", latin: "kakvoto", englishmeaning: "whatever, what" },
    { rank: 212, cyrillic: "говори", latin: "govori", englishmeaning: "speaks, talk" },
    { rank: 213, cyrillic: "разбирам", latin: "razbiram", englishmeaning: "I understand" },
    { rank: 214, cyrillic: "сигурно", latin: "sigurno", englishmeaning: "probably, surely" },
    { rank: 215, cyrillic: "чакай", latin: "chakay", englishmeaning: "wait" },
    { rank: 216, cyrillic: "веднага", latin: "vednaga", englishmeaning: "immediately" },
    { rank: 217, cyrillic: "ей", latin: "ey", englishmeaning: "hey" },
    { rank: 218, cyrillic: "три", latin: "tri", englishmeaning: "three" },
    { rank: 219, cyrillic: "какъв", latin: "kakav", englishmeaning: "what kind of" },
    { rank: 220, cyrillic: "казва", latin: "kazva", englishmeaning: "says" },
    { rank: 221, cyrillic: "стана", latin: "stana", englishmeaning: "became, happened" },
    { rank: 222, cyrillic: "утре", latin: "utre", englishmeaning: "tomorrow" },
    { rank: 223, cyrillic: "дай", latin: "day", englishmeaning: "give" },
    { rank: 224, cyrillic: "добро", latin: "dobro", englishmeaning: "good" },
    { rank: 225, cyrillic: "знаете", latin: "znaete", englishmeaning: "you know" },
    { rank: 226, cyrillic: "говоря", latin: "govorya", englishmeaning: "I speak" },
    { rank: 227, cyrillic: "била", latin: "bila", englishmeaning: "was, has been" },
    { rank: 228, cyrillic: "предвид", latin: "predvid", englishmeaning: "in mind" },
    { rank: 229, cyrillic: "казвам", latin: "kazvam", englishmeaning: "I say" },
    { rank: 230, cyrillic: "колата", latin: "kolata", englishmeaning: "the car" },
    { rank: 231, cyrillic: "имате", latin: "imate", englishmeaning: "you have" },
    { rank: 232, cyrillic: "себе", latin: "sebe", englishmeaning: "self" },
    { rank: 233, cyrillic: "момиче", latin: "momiche", englishmeaning: "girl" },
    { rank: 234, cyrillic: "мамо", latin: "mamo", englishmeaning: "mom" },
    { rank: 235, cyrillic: "стане", latin: "stane", englishmeaning: "becomes, happens" },
    { rank: 236, cyrillic: "харесва", latin: "haresva", englishmeaning: "likes" },
    { rank: 237, cyrillic: "случи", latin: "sluchi", englishmeaning: "happened" },
    { rank: 238, cyrillic: "нощ", latin: "nosht", englishmeaning: "night" },
    { rank: 239, cyrillic: "било", latin: "bilo", englishmeaning: "was, has been" },
    { rank: 240, cyrillic: "работата", latin: "rabotata", englishmeaning: "the work, the job" },
    { rank: 241, cyrillic: "каква", latin: "kakva", englishmeaning: "what kind of" },
    { rank: 242, cyrillic: "говориш", latin: "govorish", englishmeaning: "you speak" },
    { rank: 243, cyrillic: "бе", latin: "be", englishmeaning: "was, hey" },
    { rank: 244, cyrillic: "сигурен", latin: "siguren", englishmeaning: "sure" },
    { rank: 245, cyrillic: "искате", latin: "iskate", englishmeaning: "you want" },
    { rank: 246, cyrillic: "скъпа", latin: "skapa", englishmeaning: "dear, expensive" },
    { rank: 247, cyrillic: "филм", latin: "film", englishmeaning: "film" },
    { rank: 248, cyrillic: "цена", latin: "tsena", englishmeaning: "price" },
    { rank: 249, cyrillic: "любов", latin: "lyubov", englishmeaning: "love" },
    { rank: 250, cyrillic: "шофьор", latin: "shofyor", englishmeaning: "driver" }
  ];

  const HIKING_WORD_SOURCE = [
    { rank: 1, cyrillic: "влак", latin: "vlak", englishmeaning: "train" },
    { rank: 2, cyrillic: "автобус", latin: "avtobus", englishmeaning: "bus" },
    { rank: 3, cyrillic: "закъснение", latin: "zakasnenie", englishmeaning: "delay" },
    { rank: 4, cyrillic: "спешен случай", latin: "speshen sluchay", englishmeaning: "emergency" },
    { rank: 5, cyrillic: "гръм", latin: "gram", englishmeaning: "thunder" },
    { rank: 6, cyrillic: "лошо време", latin: "losho vreme", englishmeaning: "bad weather" },
    { rank: 7, cyrillic: "крака", latin: "kraka", englishmeaning: "feet" },
    { rank: 8, cyrillic: "уморен", latin: "umoren", englishmeaning: "tired" },
    { rank: 9, cyrillic: "отпочинал", latin: "otpochinal", englishmeaning: "well rested" },
    { rank: 10, cyrillic: "свеж", latin: "svezh", englishmeaning: "fresh" },
    { rank: 11, cyrillic: "вода", latin: "voda", englishmeaning: "water" },
    { rank: 12, cyrillic: "планина", latin: "planina", englishmeaning: "mountain" },
    { rank: 13, cyrillic: "пътека", latin: "pateka", englishmeaning: "trail" },
    { rank: 14, cyrillic: "змия", latin: "zmiya", englishmeaning: "snake" },
    { rank: 15, cyrillic: "овчарско куче", latin: "ovcharsko kuche", englishmeaning: "sheep dog" },
    { rank: 16, cyrillic: "кон", latin: "kon", englishmeaning: "horse" },
    { rank: 17, cyrillic: "връх", latin: "vrah", englishmeaning: "mountain peak" },
    { rank: 18, cyrillic: "хижа бобиком", latin: "hizha bobikom", englishmeaning: "bobikom hut" },
    { rank: 19, cyrillic: "хижа ком нова", latin: "hizha kom nova", englishmeaning: "kom hut new" },
    { rank: 20, cyrillic: "хижа ком стара", latin: "hizha kom stara", englishmeaning: "kom hut old" },
    { rank: 21, cyrillic: "петрохан", latin: "petrohan", englishmeaning: "petrohan creative house" },
    { rank: 22, cyrillic: "хижа пробойница", latin: "hizha proboynitsa", englishmeaning: "proboynitsa hut" },
    { rank: 23, cyrillic: "хижа тръстеная", latin: "hizha trastenaya", englishmeaning: "trastenaya hut" },
    { rank: 24, cyrillic: "хижа лескова", latin: "hizha leskova", englishmeaning: "leskova hut" },
    { rank: 25, cyrillic: "хижа мургаш", latin: "hizha murgash", englishmeaning: "murgash hut" },
    { rank: 26, cyrillic: "хижа чавдар", latin: "hizha chavdar", englishmeaning: "chavdar hut" },
    { rank: 27, cyrillic: "хижа мургана", latin: "hizha murgana", englishmeaning: "murgana hut" },
    { rank: 28, cyrillic: "хижа кашана", latin: "hizha kashana", englishmeaning: "kashana hut" },
    { rank: 29, cyrillic: "хижа свищиплаз", latin: "hizha svishtiplaz", englishmeaning: "svishtiplaz hut" },
    { rank: 30, cyrillic: "хижа момина поляна", latin: "hizha momina polyana", englishmeaning: "momina polyana hut" },
    { rank: 31, cyrillic: "хижа иванина поляна", latin: "hizha ivanina polyana", englishmeaning: "ivanina polyana hut" },
    { rank: 32, cyrillic: "хижа бенковски", latin: "hizha benkovski", englishmeaning: "benkovski hut" },
    { rank: 33, cyrillic: "хижа вежен", latin: "hizha vezhen", englishmeaning: "vezhen hut" },
    { rank: 34, cyrillic: "хижа ехо", latin: "hizha eho", englishmeaning: "echo hut" },
    { rank: 35, cyrillic: "хижа козята стена", latin: "hizha kozyata stena", englishmeaning: "kozya stena hut" },
    { rank: 36, cyrillic: "заслон орлово гнездо", latin: "zaslon orlovo gnezdo", englishmeaning: "orlovo gnezdo shelter" },
    { rank: 37, cyrillic: "хижа пешова мъка", latin: "hizha peshova maka", englishmeaning: "peshova muka hut" },
    { rank: 38, cyrillic: "хижа дерменка", latin: "hizha dermenka", englishmeaning: "dermenka hut" },
    { rank: 39, cyrillic: "хижа добрила", latin: "hizha dobrila", englishmeaning: "dobrila hut" },
    { rank: 40, cyrillic: "заслон амбарица", latin: "zaslon ambaritsa", englishmeaning: "ambaritsa shelter" },
    { rank: 41, cyrillic: "хижа васил левски", latin: "hizha vasil levski", englishmeaning: "vasil levski hut" },
    { rank: 42, cyrillic: "заслон ботев", latin: "zaslon botev", englishmeaning: "botev shelter" },
    { rank: 43, cyrillic: "заслон маринка", latin: "zaslon marinka", englishmeaning: "marinka shelter" },
    { rank: 44, cyrillic: "заслон михайлов", latin: "zaslon mihaylov", englishmeaning: "mihaylov shelter" },
    { rank: 45, cyrillic: "хижа тъжа", latin: "hizha tazha", englishmeaning: "tazha hut" },
    { rank: 46, cyrillic: "хижа мандрата", latin: "hizha mandrata", englishmeaning: "mandrata hut" },
    { rank: 47, cyrillic: "хижа мазалат", latin: "hizha mazalat", englishmeaning: "mazalat hut" },
    { rank: 48, cyrillic: "хижа партизанска песен", latin: "hizha partizanska pesen", englishmeaning: "partizanska pesen hut" },
    { rank: 49, cyrillic: "хижа узана", latin: "hizha uzana", englishmeaning: "uzana hut" },
    { rank: 50, cyrillic: "хижа бузлуджа стара", latin: "hizha buzludzha stara", englishmeaning: "buzludzha hut old" },
    { rank: 51, cyrillic: "хижа бузлуджа нова", latin: "hizha buzludzha nova", englishmeaning: "buzludzha hut new" },
    { rank: 52, cyrillic: "хижа българка", latin: "hizha balgarka", englishmeaning: "balgarka hut" },
    { rank: 53, cyrillic: "хижа планинец", latin: "hizha planinets", englishmeaning: "planinets hut" },
    { rank: 54, cyrillic: "хижа кръстец", latin: "hizha krastets", englishmeaning: "krastets hut" },
    { rank: 55, cyrillic: "хижа грамадлива", latin: "hizha gramadliva", englishmeaning: "gramadliva hut" },
    { rank: 56, cyrillic: "хижа химик", latin: "hizha himik", englishmeaning: "himik hut" },
    { rank: 57, cyrillic: "хижа предела", latin: "hizha predela", englishmeaning: "predela hut" },
    { rank: 58, cyrillic: "заслон караиваново хорище", latin: "zaslon karaivanovo horishte", englishmeaning: "karaivanovo horishte shelter" },
    { rank: 59, cyrillic: "хижа буковец", latin: "hizha bukovets", englishmeaning: "bukovets hut" },
    { rank: 60, cyrillic: "хижа чумерна", latin: "hizha chumerna", englishmeaning: "chumerna hut" },
    { rank: 61, cyrillic: "заслон вратник", latin: "zaslon vratnik", englishmeaning: "vratnik shelter" },
    { rank: 62, cyrillic: "върбишки проход", latin: "varbishki prohod", englishmeaning: "varbishki pass hut" },
    { rank: 63, cyrillic: "заслон хазим горския", latin: "zaslon hazim gorskiya", englishmeaning: "hazim gorskiya shelter" },
    { rank: 64, cyrillic: "хижа топчийско", latin: "hizha topchiysko", englishmeaning: "topchiysko hut" },
    { rank: 65, cyrillic: "козичино", latin: "kozichino", englishmeaning: "kozichino tourist dormitory" },
    { rank: 66, cyrillic: "емона", latin: "emona", englishmeaning: "emona area near cape emine" },
    { rank: 67, cyrillic: "фенерче", latin: "fenerche", englishmeaning: "flashlight" },
    { rank: 68, cyrillic: "термобельо", latin: "termobelyo", englishmeaning: "thermal underwear" },
    { rank: 69, cyrillic: "южен склон", latin: "yuzhen sklon", englishmeaning: "southern slope" },
    { rank: 70, cyrillic: "пещера", latin: "peshtera", englishmeaning: "cave" },
    { rank: 71, cyrillic: "нощувка", latin: "noshtuvka", englishmeaning: "overnight stay" },
    { rank: 72, cyrillic: "филтър за вода", latin: "filtar za voda", englishmeaning: "water filter" },
    { rank: 73, cyrillic: "слънцезащита", latin: "slantsezashtita", englishmeaning: "sun protection" },
    { rank: 74, cyrillic: "каньон", latin: "kanyon", englishmeaning: "canyon" },
    { rank: 75, cyrillic: "южен вятър", latin: "yuzhen vyatar", englishmeaning: "southern wind" },
    { rank: 76, cyrillic: "шофьор", latin: "shofyor", englishmeaning: "driver" },
    { rank: 77, cyrillic: "чайник", latin: "chaynik", englishmeaning: "kettle" },
    { rank: 78, cyrillic: "южен маршрут", latin: "yuzhen marshrut", englishmeaning: "southern route" },
    { rank: 79, cyrillic: "югоизточен склон", latin: "yugoiztochen sklon", englishmeaning: "southeastern slope" },
    { rank: 80, cyrillic: "термофолио", latin: "termofolio", englishmeaning: "emergency thermal blanket" },
    { rank: 81, cyrillic: "флисово яке", latin: "flisovo yake", englishmeaning: "fleece jacket" },
    { rank: 82, cyrillic: "каньонинг", latin: "kanyoning", englishmeaning: "canyoning" },
    { rank: 83, cyrillic: "планински водач", latin: "planinski vodach", englishmeaning: "mountain guide" }
  ];

  const ALPHABET_WORD_SOURCE = [
    { rank: 1, cyrillic: "а", latin: "a", englishmeaning: "Cyrillic letter а" },
    { rank: 2, cyrillic: "б", latin: "b", englishmeaning: "Cyrillic letter б" },
    { rank: 3, cyrillic: "в", latin: "v", englishmeaning: "Cyrillic letter в" },
    { rank: 4, cyrillic: "г", latin: "g", englishmeaning: "Cyrillic letter г" },
    { rank: 5, cyrillic: "д", latin: "d", englishmeaning: "Cyrillic letter д" },
    { rank: 6, cyrillic: "е", latin: "e", englishmeaning: "Cyrillic letter е" },
    { rank: 7, cyrillic: "ж", latin: "zh", englishmeaning: "Cyrillic letter ж" },
    { rank: 8, cyrillic: "з", latin: "z", englishmeaning: "Cyrillic letter з" },
    { rank: 9, cyrillic: "и", latin: "i", englishmeaning: "Cyrillic letter и" },
    { rank: 10, cyrillic: "й", latin: "y", englishmeaning: "Cyrillic letter й" },
    { rank: 11, cyrillic: "к", latin: "k", englishmeaning: "Cyrillic letter к" },
    { rank: 12, cyrillic: "л", latin: "l", englishmeaning: "Cyrillic letter л" },
    { rank: 13, cyrillic: "м", latin: "m", englishmeaning: "Cyrillic letter м" },
    { rank: 14, cyrillic: "н", latin: "n", englishmeaning: "Cyrillic letter н" },
    { rank: 15, cyrillic: "о", latin: "o", englishmeaning: "Cyrillic letter о" },
    { rank: 16, cyrillic: "п", latin: "p", englishmeaning: "Cyrillic letter п" },
    { rank: 17, cyrillic: "р", latin: "r", englishmeaning: "Cyrillic letter р" },
    { rank: 18, cyrillic: "с", latin: "s", englishmeaning: "Cyrillic letter с" },
    { rank: 19, cyrillic: "т", latin: "t", englishmeaning: "Cyrillic letter т" },
    { rank: 20, cyrillic: "у", latin: "u", englishmeaning: "Cyrillic letter у" },
    { rank: 21, cyrillic: "ф", latin: "f", englishmeaning: "Cyrillic letter ф" },
    { rank: 22, cyrillic: "х", latin: "h", englishmeaning: "Cyrillic letter х" },
    { rank: 23, cyrillic: "ц", latin: "ts", englishmeaning: "Cyrillic letter ц" },
    { rank: 24, cyrillic: "ч", latin: "ch", englishmeaning: "Cyrillic letter ч" },
    { rank: 25, cyrillic: "ш", latin: "sh", englishmeaning: "Cyrillic letter ш" },
    { rank: 26, cyrillic: "щ", latin: "sht", englishmeaning: "Cyrillic letter щ" },
    { rank: 27, cyrillic: "ъ", latin: "a", englishmeaning: "Cyrillic letter ъ" },
    { rank: 28, cyrillic: "ь", latin: "y", englishmeaning: "Cyrillic letter ь" },
    { rank: 29, cyrillic: "ю", latin: "yu", englishmeaning: "Cyrillic letter ю" },
    { rank: 30, cyrillic: "я", latin: "ya", englishmeaning: "Cyrillic letter я" }
  ];

  window.CYRILLIC_TRAINER_DATA = {
    source: {
      wordFrequency: "https://github.com/hermitdave/FrequencyWords/blob/master/content/2018/bg/bg_50k.txt",
      hikingHuts: "https://kom-emine.bg/huts-all-en/?lang=en",
      note: "Common ranks 247-250 replace less frequent source words to cover all lowercase Bulgarian Cyrillic letters."
    },
    letterTransliterations: LETTER_TRANSLITERATIONS,
    letterOptions: LETTER_OPTIONS,
    wordSource: WORD_SOURCE,
    datasets: [
      { id: "1", label: "top 250 words", wordSource: WORD_SOURCE },
      { id: "2", label: "Hiking E3 Kom-Emine words", wordSource: HIKING_WORD_SOURCE },
      { id: "3", label: "alphabet letters", wordSource: ALPHABET_WORD_SOURCE }
    ]
  };
}());
