(function () {
  "use strict";

  const LETTER_TRANSLITERATIONS = [
    { cyrillic: "а", latin: "a", cyrillicToLatinMustAsk: ["o", "e", "u"], latinToCyrillicMustAsk: ["ъ", "о", "е", "у"] },
    { cyrillic: "б", latin: "b", cyrillicToLatinMustAsk: ["v", "d", "g"], latinToCyrillicMustAsk: ["в", "д", "г"] },
    { cyrillic: "в", latin: "v", cyrillicToLatinMustAsk: ["b", "w", "f"], latinToCyrillicMustAsk: ["б", "ъ", "ь", "ф"] },
    { cyrillic: "г", latin: "g", cyrillicToLatinMustAsk: ["r", "h", "k"], latinToCyrillicMustAsk: ["р", "х", "к"] },
    { cyrillic: "д", latin: "d", cyrillicToLatinMustAsk: ["g", "a", "t", "l"], latinToCyrillicMustAsk: ["г", "а", "ъ", "т"] },
    { cyrillic: "е", latin: "e", cyrillicToLatinMustAsk: ["i", "y", "a"], latinToCyrillicMustAsk: ["и", "й", "ь", "а"] },
    { cyrillic: "ж", latin: "zh", cyrillicToLatinMustAsk: ["sh", "ch", "z", "j"], latinToCyrillicMustAsk: ["ш", "ч", "з"] },
    { cyrillic: "з", latin: "z", cyrillicToLatinMustAsk: ["s", "e", "zh"], latinToCyrillicMustAsk: ["с", "е", "ж"] },
    { cyrillic: "и", latin: "i", cyrillicToLatinMustAsk: ["n", "u", "y"], latinToCyrillicMustAsk: ["н", "у", "й", "ь"] },
    { cyrillic: "й", latin: "y", cyrillicToLatinMustAsk: ["i", "u", "j"], latinToCyrillicMustAsk: ["ь", "и", "у"] },
    { cyrillic: "к", latin: "k", cyrillicToLatinMustAsk: ["x", "h", "q"], latinToCyrillicMustAsk: ["х"] },
    { cyrillic: "л", latin: "l", cyrillicToLatinMustAsk: ["r", "m", "n"], latinToCyrillicMustAsk: ["р", "м", "н"] },
    { cyrillic: "м", latin: "m", cyrillicToLatinMustAsk: ["n", "h", "l"], latinToCyrillicMustAsk: ["н", "х", "л"] },
    { cyrillic: "н", latin: "n", cyrillicToLatinMustAsk: ["h", "m", "u"], latinToCyrillicMustAsk: ["х", "м", "у"] },
    { cyrillic: "о", latin: "o", cyrillicToLatinMustAsk: ["a", "e", "u"], latinToCyrillicMustAsk: ["а", "ъ", "е", "у"] },
    { cyrillic: "п", latin: "p", cyrillicToLatinMustAsk: ["n", "u", "r", "b"], latinToCyrillicMustAsk: ["н", "у", "р", "б"] },
    { cyrillic: "р", latin: "r", cyrillicToLatinMustAsk: ["p", "b", "l"], latinToCyrillicMustAsk: ["п", "б", "л"] },
    { cyrillic: "с", latin: "s", cyrillicToLatinMustAsk: ["c", "z", "k"], latinToCyrillicMustAsk: ["з", "к"] },
    { cyrillic: "т", latin: "t", cyrillicToLatinMustAsk: ["m", "d", "n"], latinToCyrillicMustAsk: ["м", "д", "н"] },
    { cyrillic: "у", latin: "u", cyrillicToLatinMustAsk: ["y", "v", "w"], latinToCyrillicMustAsk: ["й", "ь", "в"] },
    { cyrillic: "ф", latin: "f", cyrillicToLatinMustAsk: ["o", "p", "v"], latinToCyrillicMustAsk: ["о", "п", "в"] },
    { cyrillic: "х", latin: "h", cyrillicToLatinMustAsk: ["x", "k", "ch"], latinToCyrillicMustAsk: ["к", "ч"] },
    { cyrillic: "ц", latin: "ts", cyrillicToLatinMustAsk: ["c", "s", "ch"], latinToCyrillicMustAsk: ["с", "ч"] },
    { cyrillic: "ч", latin: "ch", cyrillicToLatinMustAsk: ["sh", "ts", "c"], latinToCyrillicMustAsk: ["ш", "ц"] },
    { cyrillic: "ш", latin: "sh", cyrillicToLatinMustAsk: ["ch", "sht", "s"], latinToCyrillicMustAsk: ["ч", "щ", "с"] },
    { cyrillic: "щ", latin: "sht", cyrillicToLatinMustAsk: ["sh", "ch", "ts"], latinToCyrillicMustAsk: ["ш", "ч", "ц"] },
    { cyrillic: "ъ", latin: "a", cyrillicToLatinMustAsk: ["u", "y", "o"], latinToCyrillicMustAsk: ["а", "у", "й", "ь"] },
    { cyrillic: "ь", latin: "y", cyrillicToLatinMustAsk: ["b", "i", "u"], latinToCyrillicMustAsk: ["й", "б", "и", "у"] },
    { cyrillic: "ю", latin: "yu", cyrillicToLatinMustAsk: ["u", "ya", "y"], latinToCyrillicMustAsk: ["у", "я", "й", "ь"] },
    { cyrillic: "я", latin: "ya", cyrillicToLatinMustAsk: ["r", "a", "yu"], latinToCyrillicMustAsk: ["р", "а", "ъ", "ю"] },
    { cyrillic: "А", latin: "A", cyrillicToLatinMustAsk: ["O", "E", "U"], latinToCyrillicMustAsk: ["Ъ", "О", "Е", "У"] },
    { cyrillic: "Б", latin: "B", cyrillicToLatinMustAsk: ["V", "D", "G"], latinToCyrillicMustAsk: ["В", "Д", "Г"] },
    { cyrillic: "В", latin: "V", cyrillicToLatinMustAsk: ["B", "W", "F"], latinToCyrillicMustAsk: ["Б", "Ъ", "Ь", "Ф"] },
    { cyrillic: "Г", latin: "G", cyrillicToLatinMustAsk: ["L", "T", "K"], latinToCyrillicMustAsk: ["Л", "Т", "К"] },
    { cyrillic: "Д", latin: "D", cyrillicToLatinMustAsk: ["A", "L", "G", "T"], latinToCyrillicMustAsk: ["А", "Ъ", "Л", "Г"] },
    { cyrillic: "Е", latin: "E", cyrillicToLatinMustAsk: ["I", "Y", "A"], latinToCyrillicMustAsk: ["И", "Й", "Ь", "А"] },
    { cyrillic: "Ж", latin: "ZH", cyrillicToLatinMustAsk: ["SH", "CH", "Z", "J"], latinToCyrillicMustAsk: ["Ш", "Ч", "З"] },
    { cyrillic: "З", latin: "Z", cyrillicToLatinMustAsk: ["S", "E", "ZH"], latinToCyrillicMustAsk: ["С", "Е", "Ж"] },
    { cyrillic: "И", latin: "I", cyrillicToLatinMustAsk: ["N", "U", "Y"], latinToCyrillicMustAsk: ["Н", "У", "Й", "Ь"] },
    { cyrillic: "Й", latin: "Y", cyrillicToLatinMustAsk: ["I", "N", "U"], latinToCyrillicMustAsk: ["Ь", "И", "Н", "У"] },
    { cyrillic: "К", latin: "K", cyrillicToLatinMustAsk: ["X", "H", "Q"], latinToCyrillicMustAsk: ["Х"] },
    { cyrillic: "Л", latin: "L", cyrillicToLatinMustAsk: ["A", "M", "N"], latinToCyrillicMustAsk: ["А", "Ъ", "М", "Н"] },
    { cyrillic: "М", latin: "M", cyrillicToLatinMustAsk: ["N", "H", "L"], latinToCyrillicMustAsk: ["Н", "Х", "Л"] },
    { cyrillic: "Н", latin: "N", cyrillicToLatinMustAsk: ["H", "M", "U"], latinToCyrillicMustAsk: ["Х", "М", "У"] },
    { cyrillic: "О", latin: "O", cyrillicToLatinMustAsk: ["A", "E", "U"], latinToCyrillicMustAsk: ["А", "Ъ", "Е", "У"] },
    { cyrillic: "П", latin: "P", cyrillicToLatinMustAsk: ["N", "U", "R", "B"], latinToCyrillicMustAsk: ["Н", "У", "Р", "Б"] },
    { cyrillic: "Р", latin: "R", cyrillicToLatinMustAsk: ["P", "B", "L"], latinToCyrillicMustAsk: ["П", "Б", "Л"] },
    { cyrillic: "С", latin: "S", cyrillicToLatinMustAsk: ["C", "Z", "K"], latinToCyrillicMustAsk: ["З", "К"] },
    { cyrillic: "Т", latin: "T", cyrillicToLatinMustAsk: ["M", "D", "N"], latinToCyrillicMustAsk: ["М", "Д", "Н"] },
    { cyrillic: "У", latin: "U", cyrillicToLatinMustAsk: ["Y", "V", "W"], latinToCyrillicMustAsk: ["Й", "Ь", "В"] },
    { cyrillic: "Ф", latin: "F", cyrillicToLatinMustAsk: ["O", "P", "V"], latinToCyrillicMustAsk: ["О", "П", "В"] },
    { cyrillic: "Х", latin: "H", cyrillicToLatinMustAsk: ["X", "K", "CH"], latinToCyrillicMustAsk: ["К", "Ч"] },
    { cyrillic: "Ц", latin: "TS", cyrillicToLatinMustAsk: ["C", "S", "CH", "U"], latinToCyrillicMustAsk: ["С", "Ч", "У"] },
    { cyrillic: "Ч", latin: "CH", cyrillicToLatinMustAsk: ["SH", "TS", "C"], latinToCyrillicMustAsk: ["Ш", "Ц"] },
    { cyrillic: "Ш", latin: "SH", cyrillicToLatinMustAsk: ["W", "CH", "SHT", "S"], latinToCyrillicMustAsk: ["Ч", "Щ", "С"] },
    { cyrillic: "Щ", latin: "SHT", cyrillicToLatinMustAsk: ["W", "SH", "CH", "TS"], latinToCyrillicMustAsk: ["Ш", "Ч", "Ц"] },
    { cyrillic: "Ъ", latin: "A", cyrillicToLatinMustAsk: ["B", "U", "Y", "O"], latinToCyrillicMustAsk: ["А", "Б", "У", "Й"] },
    { cyrillic: "Ь", latin: "Y", cyrillicToLatinMustAsk: ["B", "I", "U"], latinToCyrillicMustAsk: ["Й", "Б", "И", "У"] },
    { cyrillic: "Ю", latin: "YU", cyrillicToLatinMustAsk: ["U", "YA", "Y", "O"], latinToCyrillicMustAsk: ["У", "Я", "Й", "Ь"] },
    { cyrillic: "Я", latin: "YA", cyrillicToLatinMustAsk: ["R", "A", "YU"], latinToCyrillicMustAsk: ["Р", "А", "Ъ", "Ю"] }
  ];

  const LETTER_OPTIONS = [
    "a",
    "b",
    "c",
    "ch",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "p",
    "q",
    "r",
    "s",
    "sh",
    "sht",
    "t",
    "ts",
    "u",
    "v",
    "w",
    "x",
    "y",
    "ya",
    "yu",
    "z",
    "zh"
  ];

  const WORD_SOURCE = [
    { rank: 1, cyrillic: "да", latin: "da", phonetic: "da", englishmeaning: "yes" },
    { rank: 2, cyrillic: "е", latin: "e", phonetic: "eh", englishmeaning: "is" },
    { rank: 3, cyrillic: "не", latin: "ne", phonetic: "neh", englishmeaning: "no, not" },
    { rank: 4, cyrillic: "се", latin: "se", phonetic: "seh", englishmeaning: "self, reflexive particle" },
    { rank: 5, cyrillic: "и", latin: "i", phonetic: "ee", englishmeaning: "and" },
    { rank: 6, cyrillic: "на", latin: "na", phonetic: "na", englishmeaning: "of, on, to" },
    { rank: 7, cyrillic: "си", latin: "si", phonetic: "see", englishmeaning: "oneself, own" },
    { rank: 8, cyrillic: "за", latin: "za", phonetic: "za", englishmeaning: "for, about" },
    { rank: 9, cyrillic: "ще", latin: "shte", phonetic: "shteh", englishmeaning: "will" },
    { rank: 10, cyrillic: "че", latin: "che", phonetic: "cheh", englishmeaning: "that" },
    { rank: 11, cyrillic: "това", latin: "tova", phonetic: "tova", englishmeaning: "this, that" },
    { rank: 12, cyrillic: "ли", latin: "li", phonetic: "lee", englishmeaning: "question particle" },
    { rank: 13, cyrillic: "в", latin: "v", phonetic: "v", englishmeaning: "in" },
    { rank: 14, cyrillic: "ти", latin: "ti", phonetic: "tee", englishmeaning: "you" },
    { rank: 15, cyrillic: "от", latin: "ot", phonetic: "ot", englishmeaning: "from, by" },
    { rank: 16, cyrillic: "ми", latin: "mi", phonetic: "mee", englishmeaning: "my, to me" },
    { rank: 17, cyrillic: "с", latin: "s", phonetic: "s", englishmeaning: "with" },
    { rank: 18, cyrillic: "какво", latin: "kakvo", phonetic: "kakvo", englishmeaning: "what" },
    { rank: 19, cyrillic: "го", latin: "go", phonetic: "go", englishmeaning: "him, it" },
    { rank: 20, cyrillic: "съм", latin: "sam", phonetic: "suhm", englishmeaning: "I am" },
    { rank: 21, cyrillic: "но", latin: "no", phonetic: "no", englishmeaning: "but" },
    { rank: 22, cyrillic: "аз", latin: "az", phonetic: "az", englishmeaning: "I" },
    { rank: 23, cyrillic: "те", latin: "te", phonetic: "teh", englishmeaning: "they, them" },
    { rank: 24, cyrillic: "трябва", latin: "tryabva", phonetic: "tryabva", englishmeaning: "must, should" },
    { rank: 25, cyrillic: "добре", latin: "dobre", phonetic: "dobreh", englishmeaning: "well, good" },
    { rank: 26, cyrillic: "ме", latin: "me", phonetic: "meh", englishmeaning: "me" },
    { rank: 27, cyrillic: "са", latin: "sa", phonetic: "sa", englishmeaning: "are" },
    { rank: 28, cyrillic: "няма", latin: "nyama", phonetic: "nyama", englishmeaning: "there is no, will not" },
    { rank: 29, cyrillic: "може", latin: "mozhe", phonetic: "mozheh", englishmeaning: "can, may" },
    { rank: 30, cyrillic: "ако", latin: "ako", phonetic: "ako", englishmeaning: "if" },
    { rank: 31, cyrillic: "тук", latin: "tuk", phonetic: "took", englishmeaning: "here" },
    { rank: 32, cyrillic: "така", latin: "taka", phonetic: "taka", englishmeaning: "so, like this" },
    { rank: 33, cyrillic: "а", latin: "a", phonetic: "a", englishmeaning: "and, but" },
    { rank: 34, cyrillic: "ви", latin: "vi", phonetic: "vee", englishmeaning: "you, your" },
    { rank: 35, cyrillic: "като", latin: "kato", phonetic: "kato", englishmeaning: "as, like" },
    { rank: 36, cyrillic: "много", latin: "mnogo", phonetic: "mnogo", englishmeaning: "much, many, very" },
    { rank: 37, cyrillic: "той", latin: "toy", phonetic: "toy", englishmeaning: "he" },
    { rank: 38, cyrillic: "по", latin: "po", phonetic: "po", englishmeaning: "along, by, more" },
    { rank: 39, cyrillic: "има", latin: "ima", phonetic: "eema", englishmeaning: "there is, has" },
    { rank: 40, cyrillic: "беше", latin: "beshe", phonetic: "behsheh", englishmeaning: "was" },
    { rank: 41, cyrillic: "нещо", latin: "neshto", phonetic: "nehshto", englishmeaning: "something" },
    { rank: 42, cyrillic: "му", latin: "mu", phonetic: "moo", englishmeaning: "his, to him" },
    { rank: 43, cyrillic: "как", latin: "kak", phonetic: "kak", englishmeaning: "how" },
    { rank: 44, cyrillic: "защо", latin: "zashto", phonetic: "zashto", englishmeaning: "why" },
    { rank: 45, cyrillic: "ни", latin: "ni", phonetic: "nee", englishmeaning: "us, our" },
    { rank: 46, cyrillic: "я", latin: "ya", phonetic: "ya", englishmeaning: "her, it" },
    { rank: 47, cyrillic: "знам", latin: "znam", phonetic: "znam", englishmeaning: "I know" },
    { rank: 48, cyrillic: "само", latin: "samo", phonetic: "samo", englishmeaning: "only" },
    { rank: 49, cyrillic: "всичко", latin: "vsichko", phonetic: "vseechko", englishmeaning: "everything" },
    { rank: 50, cyrillic: "мен", latin: "men", phonetic: "mehn", englishmeaning: "me" },
    { rank: 51, cyrillic: "сега", latin: "sega", phonetic: "sehga", englishmeaning: "now" },
    { rank: 52, cyrillic: "теб", latin: "teb", phonetic: "tehb", englishmeaning: "you" },
    { rank: 53, cyrillic: "тя", latin: "tya", phonetic: "tya", englishmeaning: "she" },
    { rank: 54, cyrillic: "което", latin: "koeto", phonetic: "koehto", englishmeaning: "which, that" },
    { rank: 55, cyrillic: "искам", latin: "iskam", phonetic: "eeskam", englishmeaning: "I want" },
    { rank: 56, cyrillic: "мога", latin: "moga", phonetic: "moga", englishmeaning: "I can" },
    { rank: 57, cyrillic: "още", latin: "oshte", phonetic: "oshteh", englishmeaning: "more, still, yet" },
    { rank: 58, cyrillic: "когато", latin: "kogato", phonetic: "kogato", englishmeaning: "when" },
    { rank: 59, cyrillic: "до", latin: "do", phonetic: "do", englishmeaning: "to, until" },
    { rank: 60, cyrillic: "ги", latin: "gi", phonetic: "gee", englishmeaning: "them" },
    { rank: 61, cyrillic: "този", latin: "tozi", phonetic: "tozee", englishmeaning: "this" },
    { rank: 62, cyrillic: "просто", latin: "prosto", phonetic: "prosto", englishmeaning: "simply, just" },
    { rank: 63, cyrillic: "сте", latin: "ste", phonetic: "steh", englishmeaning: "you are" },
    { rank: 64, cyrillic: "или", latin: "ili", phonetic: "eelee", englishmeaning: "or" },
    { rank: 65, cyrillic: "къде", latin: "kade", phonetic: "kuh-'deh", englishmeaning: "where" },
    { rank: 66, cyrillic: "би", latin: "bi", phonetic: "bee", englishmeaning: "would" },
    { rank: 67, cyrillic: "тази", latin: "tazi", phonetic: "tazee", englishmeaning: "this" },
    { rank: 68, cyrillic: "всички", latin: "vsichki", phonetic: "vseechkee", englishmeaning: "all, everyone" },
    { rank: 69, cyrillic: "благодаря", latin: "blagodarya", phonetic: "blagodarya", englishmeaning: "thank you" },
    { rank: 70, cyrillic: "нали", latin: "nali", phonetic: "nalee", englishmeaning: "right, is it not" },
    { rank: 71, cyrillic: "сме", latin: "sme", phonetic: "smeh", englishmeaning: "we are" },
    { rank: 72, cyrillic: "нищо", latin: "nishto", phonetic: "neeshto", englishmeaning: "nothing" },
    { rank: 73, cyrillic: "толкова", latin: "tolkova", phonetic: "tolkova", englishmeaning: "so much" },
    { rank: 74, cyrillic: "знаеш", latin: "znaesh", phonetic: "znaehsh", englishmeaning: "you know" },
    { rank: 75, cyrillic: "един", latin: "edin", phonetic: "ehdeen", englishmeaning: "one, a" },
    { rank: 76, cyrillic: "защото", latin: "zashtoto", phonetic: "zashtoto", englishmeaning: "because" },
    { rank: 77, cyrillic: "след", latin: "sled", phonetic: "slehd", englishmeaning: "after" },
    { rank: 78, cyrillic: "там", latin: "tam", phonetic: "tam", englishmeaning: "there" },
    { rank: 79, cyrillic: "време", latin: "vreme", phonetic: "vrehmeh", englishmeaning: "time, weather" },
    { rank: 80, cyrillic: "който", latin: "koyto", phonetic: "koyto", englishmeaning: "who, which" },
    { rank: 81, cyrillic: "искаш", latin: "iskash", phonetic: "eeskash", englishmeaning: "you want" },
    { rank: 82, cyrillic: "мисля", latin: "mislya", phonetic: "meeslya", englishmeaning: "I think" },
    { rank: 83, cyrillic: "кой", latin: "koy", phonetic: "koy", englishmeaning: "who" },
    { rank: 84, cyrillic: "малко", latin: "malko", phonetic: "malko", englishmeaning: "little, a little" },
    { rank: 85, cyrillic: "имам", latin: "imam", phonetic: "eemam", englishmeaning: "I have" },
    { rank: 86, cyrillic: "преди", latin: "predi", phonetic: "prehdee", englishmeaning: "before" },
    { rank: 87, cyrillic: "хайде", latin: "hayde", phonetic: "khaydeh", englishmeaning: "come on" },
    { rank: 88, cyrillic: "вече", latin: "veche", phonetic: "vehcheh", englishmeaning: "already" },
    { rank: 89, cyrillic: "тези", latin: "tezi", phonetic: "tehzee", englishmeaning: "these" },
    { rank: 90, cyrillic: "моля", latin: "molya", phonetic: "molya", englishmeaning: "please" },
    { rank: 91, cyrillic: "о", latin: "o", phonetic: "o", englishmeaning: "oh" },
    { rank: 92, cyrillic: "някой", latin: "nyakoy", phonetic: "nyakoy", englishmeaning: "someone" },
    { rank: 93, cyrillic: "каза", latin: "kaza", phonetic: "kaza", englishmeaning: "said" },
    { rank: 94, cyrillic: "него", latin: "nego", phonetic: "nehgo", englishmeaning: "him" },
    { rank: 95, cyrillic: "наистина", latin: "naistina", phonetic: "naeesteena", englishmeaning: "really, truly" },
    { rank: 96, cyrillic: "ние", latin: "nie", phonetic: "neeeh", englishmeaning: "we" },
    { rank: 97, cyrillic: "вие", latin: "vie", phonetic: "veeeh", englishmeaning: "you" },
    { rank: 98, cyrillic: "които", latin: "koito", phonetic: "koeeto", englishmeaning: "who, which" },
    { rank: 99, cyrillic: "й", latin: "y", phonetic: "y", englishmeaning: "her, to her" },
    { rank: 100, cyrillic: "повече", latin: "poveche", phonetic: "povehcheh", englishmeaning: "more" },
    { rank: 101, cyrillic: "съжалявам", latin: "sazhalyavam", phonetic: "suhzhalyavam", englishmeaning: "I am sorry" },
    { rank: 102, cyrillic: "тогава", latin: "togava", phonetic: "togava", englishmeaning: "then" },
    { rank: 103, cyrillic: "точно", latin: "tochno", phonetic: "tochno", englishmeaning: "exactly" },
    { rank: 104, cyrillic: "става", latin: "stava", phonetic: "stava", englishmeaning: "happens, becomes" },
    { rank: 105, cyrillic: "все", latin: "vse", phonetic: "vseh", englishmeaning: "still, always" },
    { rank: 106, cyrillic: "можеш", latin: "mozhesh", phonetic: "mozhehsh", englishmeaning: "you can" },
    { rank: 107, cyrillic: "една", latin: "edna", phonetic: "ehdna", englishmeaning: "one, a" },
    { rank: 108, cyrillic: "имаш", latin: "imash", phonetic: "eemash", englishmeaning: "you have" },
    { rank: 109, cyrillic: "към", latin: "kam", phonetic: "kuhm", englishmeaning: "toward" },
    { rank: 110, cyrillic: "без", latin: "bez", phonetic: "behz", englishmeaning: "without" },
    { rank: 111, cyrillic: "колко", latin: "kolko", phonetic: "kolko", englishmeaning: "how much, how many" },
    { rank: 112, cyrillic: "кажа", latin: "kazha", phonetic: "kazha", englishmeaning: "I say, I will say" },
    { rank: 113, cyrillic: "никога", latin: "nikoga", phonetic: "neekoga", englishmeaning: "never" },
    { rank: 114, cyrillic: "при", latin: "pri", phonetic: "pree", englishmeaning: "at, near, with" },
    { rank: 115, cyrillic: "човек", latin: "chovek", phonetic: "chovehk", englishmeaning: "person, man" },
    { rank: 116, cyrillic: "работа", latin: "rabota", phonetic: "rabota", englishmeaning: "work, job" },
    { rank: 117, cyrillic: "им", latin: "im", phonetic: "eem", englishmeaning: "them, their" },
    { rank: 118, cyrillic: "ден", latin: "den", phonetic: "dehn", englishmeaning: "day" },
    { rank: 119, cyrillic: "едно", latin: "edno", phonetic: "ehdno", englishmeaning: "one, a" },
    { rank: 120, cyrillic: "бях", latin: "byah", phonetic: "byakh", englishmeaning: "I was" },
    { rank: 121, cyrillic: "бъде", latin: "bade", phonetic: "buhdeh", englishmeaning: "be, become" },
    { rank: 122, cyrillic: "през", latin: "prez", phonetic: "prehz", englishmeaning: "through, during" },
    { rank: 123, cyrillic: "ето", latin: "eto", phonetic: "ehto", englishmeaning: "here is" },
    { rank: 124, cyrillic: "значи", latin: "znachi", phonetic: "znachee", englishmeaning: "means, so" },
    { rank: 125, cyrillic: "със", latin: "sas", phonetic: "suhs", englishmeaning: "with" },
    { rank: 126, cyrillic: "дори", latin: "dori", phonetic: "doree", englishmeaning: "even" },
    { rank: 127, cyrillic: "хора", latin: "hora", phonetic: "khora", englishmeaning: "people" },
    { rank: 128, cyrillic: "път", latin: "pat", phonetic: "puht", englishmeaning: "road, time" },
    { rank: 129, cyrillic: "както", latin: "kakto", phonetic: "kakto", englishmeaning: "as, like" },
    { rank: 130, cyrillic: "нас", latin: "nas", phonetic: "nas", englishmeaning: "us" },
    { rank: 131, cyrillic: "години", latin: "godini", phonetic: "godeenee", englishmeaning: "years" },
    { rank: 132, cyrillic: "бил", latin: "bil", phonetic: "beel", englishmeaning: "was, has been" },
    { rank: 133, cyrillic: "баща", latin: "bashta", phonetic: "bashta", englishmeaning: "father" },
    { rank: 134, cyrillic: "правиш", latin: "pravish", phonetic: "praveesh", englishmeaning: "you do, you make" },
    { rank: 135, cyrillic: "която", latin: "koyato", phonetic: "koyato", englishmeaning: "who, which" },
    { rank: 136, cyrillic: "разбира", latin: "razbira", phonetic: "razbeera", englishmeaning: "understands" },
    { rank: 137, cyrillic: "също", latin: "sashto", phonetic: "suhshto", englishmeaning: "also" },
    { rank: 138, cyrillic: "мислиш", latin: "mislish", phonetic: "meesleesh", englishmeaning: "you think" },
    { rank: 139, cyrillic: "вас", latin: "vas", phonetic: "vas", englishmeaning: "you" },
    { rank: 140, cyrillic: "ами", latin: "ami", phonetic: "amee", englishmeaning: "well" },
    { rank: 141, cyrillic: "нея", latin: "neya", phonetic: "nehya", englishmeaning: "her" },
    { rank: 142, cyrillic: "направи", latin: "napravi", phonetic: "napravee", englishmeaning: "made, did" },
    { rank: 143, cyrillic: "винаги", latin: "vinagi", phonetic: "veenagee", englishmeaning: "always" },
    { rank: 144, cyrillic: "докато", latin: "dokato", phonetic: "dokato", englishmeaning: "while, until" },
    { rank: 145, cyrillic: "имаме", latin: "imame", phonetic: "eemameh", englishmeaning: "we have" },
    { rank: 146, cyrillic: "виж", latin: "vizh", phonetic: "veezh", englishmeaning: "look, see" },
    { rank: 147, cyrillic: "всеки", latin: "vseki", phonetic: "vsehkee", englishmeaning: "every, everyone" },
    { rank: 148, cyrillic: "иска", latin: "iska", phonetic: "eeska", englishmeaning: "wants" },
    { rank: 149, cyrillic: "майка", latin: "mayka", phonetic: "mayka", englishmeaning: "mother" },
    { rank: 150, cyrillic: "казах", latin: "kazah", phonetic: "kazakh", englishmeaning: "I said" },
    { rank: 151, cyrillic: "нека", latin: "neka", phonetic: "nehka", englishmeaning: "let" },
    { rank: 152, cyrillic: "хората", latin: "horata", phonetic: "khorata", englishmeaning: "the people" },
    { rank: 153, cyrillic: "хей", latin: "hey", phonetic: "khehy", englishmeaning: "hey" },
    { rank: 154, cyrillic: "жена", latin: "zhena", phonetic: "zhehna", englishmeaning: "woman, wife" },
    { rank: 155, cyrillic: "видя", latin: "vidya", phonetic: "veedya", englishmeaning: "saw, see" },
    { rank: 156, cyrillic: "дали", latin: "dali", phonetic: "dalee", englishmeaning: "whether" },
    { rank: 157, cyrillic: "във", latin: "vav", phonetic: "vuhv", englishmeaning: "in" },
    { rank: 158, cyrillic: "никой", latin: "nikoy", phonetic: "neekoy", englishmeaning: "nobody" },
    { rank: 159, cyrillic: "пак", latin: "pak", phonetic: "pak", englishmeaning: "again" },
    { rank: 160, cyrillic: "тях", latin: "tyah", phonetic: "tyakh", englishmeaning: "them" },
    { rank: 161, cyrillic: "направя", latin: "napravya", phonetic: "napravya", englishmeaning: "I make, I do" },
    { rank: 162, cyrillic: "неща", latin: "neshta", phonetic: "nehshta", englishmeaning: "things" },
    { rank: 163, cyrillic: "кажи", latin: "kazhi", phonetic: "kazhee", englishmeaning: "say, tell" },
    { rank: 164, cyrillic: "място", latin: "myasto", phonetic: "myasto", englishmeaning: "place" },
    { rank: 165, cyrillic: "заради", latin: "zaradi", phonetic: "zaradee", englishmeaning: "because of" },
    { rank: 166, cyrillic: "прави", latin: "pravi", phonetic: "pravee", englishmeaning: "does, makes" },
    { rank: 167, cyrillic: "сър", latin: "sar", phonetic: "suhr", englishmeaning: "sir" },
    { rank: 168, cyrillic: "можем", latin: "mozhem", phonetic: "mozhehm", englishmeaning: "we can" },
    { rank: 169, cyrillic: "дяволите", latin: "dyavolite", phonetic: "dyavoleeteh", englishmeaning: "the devils, damn" },
    { rank: 170, cyrillic: "изглежда", latin: "izglezhda", phonetic: "eezglehzhda", englishmeaning: "seems, looks" },
    { rank: 171, cyrillic: "днес", latin: "dnes", phonetic: "dnehs", englishmeaning: "today" },
    { rank: 172, cyrillic: "кажеш", latin: "kazhesh", phonetic: "kazhehsh", englishmeaning: "you say, you tell" },
    { rank: 173, cyrillic: "живота", latin: "zhivota", phonetic: "zheevota", englishmeaning: "the life" },
    { rank: 174, cyrillic: "трябваше", latin: "tryabvashe", phonetic: "tryabvasheh", englishmeaning: "had to, should have" },
    { rank: 175, cyrillic: "отново", latin: "otnovo", phonetic: "otnovo", englishmeaning: "again" },
    { rank: 176, cyrillic: "татко", latin: "tatko", phonetic: "tatko", englishmeaning: "dad" },
    { rank: 177, cyrillic: "няколко", latin: "nyakolko", phonetic: "nyakolko", englishmeaning: "several" },
    { rank: 178, cyrillic: "наред", latin: "nared", phonetic: "narehd", englishmeaning: "in order, for" },
    { rank: 179, cyrillic: "боже", latin: "bozhe", phonetic: "bozheh", englishmeaning: "God, oh God" },
    { rank: 180, cyrillic: "друг", latin: "drug", phonetic: "droog", englishmeaning: "other, another" },
    { rank: 181, cyrillic: "здравей", latin: "zdravey", phonetic: "zdravehy", englishmeaning: "hello" },
    { rank: 182, cyrillic: "затова", latin: "zatova", phonetic: "zatova", englishmeaning: "therefore, that is why" },
    { rank: 183, cyrillic: "бих", latin: "bih", phonetic: "beekh", englishmeaning: "would" },
    { rank: 184, cyrillic: "доста", latin: "dosta", phonetic: "dosta", englishmeaning: "quite, enough" },
    { rank: 185, cyrillic: "обичам", latin: "obicham", phonetic: "obeecham", englishmeaning: "I love" },
    { rank: 186, cyrillic: "пари", latin: "pari", phonetic: "paree", englishmeaning: "money" },
    { rank: 187, cyrillic: "знае", latin: "znae", phonetic: "znaeh", englishmeaning: "knows" },
    { rank: 188, cyrillic: "начин", latin: "nachin", phonetic: "nacheen", englishmeaning: "way" },
    { rank: 189, cyrillic: "моя", latin: "moya", phonetic: "moya", englishmeaning: "my" },
    { rank: 190, cyrillic: "мислех", latin: "misleh", phonetic: "meeslehkh", englishmeaning: "I thought" },
    { rank: 191, cyrillic: "нужда", latin: "nuzhda", phonetic: "noozhda", englishmeaning: "need" },
    { rank: 192, cyrillic: "сам", latin: "sam", phonetic: "sam", englishmeaning: "alone, by myself" },
    { rank: 193, cyrillic: "две", latin: "dve", phonetic: "dveh", englishmeaning: "two" },
    { rank: 194, cyrillic: "дойде", latin: "doyde", phonetic: "doydeh", englishmeaning: "came" },
    { rank: 195, cyrillic: "заедно", latin: "zaedno", phonetic: "zaehdno", englishmeaning: "together" },
    { rank: 196, cyrillic: "добър", latin: "dobar", phonetic: "dobuhr", englishmeaning: "good" },
    { rank: 197, cyrillic: "ела", latin: "ela", phonetic: "ehla", englishmeaning: "come" },
    { rank: 198, cyrillic: "нямам", latin: "nyamam", phonetic: "nyamam", englishmeaning: "I do not have" },
    { rank: 199, cyrillic: "приятел", latin: "priyatel", phonetic: "preeyatehl", englishmeaning: "friend" },
    { rank: 200, cyrillic: "после", latin: "posle", phonetic: "posleh", englishmeaning: "afterwards, later" },
    { rank: 201, cyrillic: "видим", latin: "vidim", phonetic: "veedeem", englishmeaning: "we see, visible" },
    { rank: 202, cyrillic: "правя", latin: "pravya", phonetic: "pravya", englishmeaning: "I do, I make" },
    { rank: 203, cyrillic: "вечер", latin: "vecher", phonetic: "vehchehr", englishmeaning: "evening" },
    { rank: 204, cyrillic: "достатъчно", latin: "dostatachno", phonetic: "dostatuhchno", englishmeaning: "enough" },
    { rank: 205, cyrillic: "всъщност", latin: "vsashtnost", phonetic: "vsuhshtnost", englishmeaning: "actually" },
    { rank: 206, cyrillic: "исках", latin: "iskah", phonetic: "eeskakh", englishmeaning: "I wanted" },
    { rank: 207, cyrillic: "проблем", latin: "problem", phonetic: "problehm", englishmeaning: "problem" },
    { rank: 208, cyrillic: "живот", latin: "zhivot", phonetic: "zheevot", englishmeaning: "life" },
    { rank: 209, cyrillic: "нещата", latin: "neshtata", phonetic: "nehshtata", englishmeaning: "the things" },
    { rank: 210, cyrillic: "под", latin: "pod", phonetic: "pod", englishmeaning: "under" },
    { rank: 211, cyrillic: "каквото", latin: "kakvoto", phonetic: "kakvoto", englishmeaning: "whatever, what" },
    { rank: 212, cyrillic: "говори", latin: "govori", phonetic: "govoree", englishmeaning: "speaks, talk" },
    { rank: 213, cyrillic: "разбирам", latin: "razbiram", phonetic: "razbeeram", englishmeaning: "I understand" },
    { rank: 214, cyrillic: "сигурно", latin: "sigurno", phonetic: "seegoorno", englishmeaning: "probably, surely" },
    { rank: 215, cyrillic: "чакай", latin: "chakay", phonetic: "chakay", englishmeaning: "wait" },
    { rank: 216, cyrillic: "веднага", latin: "vednaga", phonetic: "vehdnaga", englishmeaning: "immediately" },
    { rank: 217, cyrillic: "ей", latin: "ey", phonetic: "ehy", englishmeaning: "hey" },
    { rank: 218, cyrillic: "три", latin: "tri", phonetic: "tree", englishmeaning: "three" },
    { rank: 219, cyrillic: "какъв", latin: "kakav", phonetic: "kakuhv", englishmeaning: "what kind of" },
    { rank: 220, cyrillic: "казва", latin: "kazva", phonetic: "kazva", englishmeaning: "says" },
    { rank: 221, cyrillic: "стана", latin: "stana", phonetic: "stana", englishmeaning: "became, happened" },
    { rank: 222, cyrillic: "утре", latin: "utre", phonetic: "ootreh", englishmeaning: "tomorrow" },
    { rank: 223, cyrillic: "дай", latin: "day", phonetic: "day", englishmeaning: "give" },
    { rank: 224, cyrillic: "добро", latin: "dobro", phonetic: "dobro", englishmeaning: "good" },
    { rank: 225, cyrillic: "знаете", latin: "znaete", phonetic: "znaehteh", englishmeaning: "you know" },
    { rank: 226, cyrillic: "говоря", latin: "govorya", phonetic: "govorya", englishmeaning: "I speak" },
    { rank: 227, cyrillic: "била", latin: "bila", phonetic: "beela", englishmeaning: "was, has been" },
    { rank: 228, cyrillic: "предвид", latin: "predvid", phonetic: "prehdveed", englishmeaning: "in mind" },
    { rank: 229, cyrillic: "казвам", latin: "kazvam", phonetic: "kazvam", englishmeaning: "I say" },
    { rank: 230, cyrillic: "колата", latin: "kolata", phonetic: "kolata", englishmeaning: "the car" },
    { rank: 231, cyrillic: "имате", latin: "imate", phonetic: "eemateh", englishmeaning: "you have" },
    { rank: 232, cyrillic: "себе", latin: "sebe", phonetic: "sehbeh", englishmeaning: "self" },
    { rank: 233, cyrillic: "момиче", latin: "momiche", phonetic: "momeecheh", englishmeaning: "girl" },
    { rank: 234, cyrillic: "мамо", latin: "mamo", phonetic: "mamo", englishmeaning: "mom" },
    { rank: 235, cyrillic: "стане", latin: "stane", phonetic: "staneh", englishmeaning: "becomes, happens" },
    { rank: 236, cyrillic: "харесва", latin: "haresva", phonetic: "kharehsva", englishmeaning: "likes" },
    { rank: 237, cyrillic: "случи", latin: "sluchi", phonetic: "sloochee", englishmeaning: "happened" },
    { rank: 238, cyrillic: "нощ", latin: "nosht", phonetic: "nosht", englishmeaning: "night" },
    { rank: 239, cyrillic: "било", latin: "bilo", phonetic: "beelo", englishmeaning: "was, has been" },
    { rank: 240, cyrillic: "работата", latin: "rabotata", phonetic: "rabotata", englishmeaning: "the work, the job" },
    { rank: 241, cyrillic: "каква", latin: "kakva", phonetic: "kakva", englishmeaning: "what kind of" },
    { rank: 242, cyrillic: "говориш", latin: "govorish", phonetic: "govoreesh", englishmeaning: "you speak" },
    { rank: 243, cyrillic: "бе", latin: "be", phonetic: "beh", englishmeaning: "was, hey" },
    { rank: 244, cyrillic: "сигурен", latin: "siguren", phonetic: "seegoorehn", englishmeaning: "sure" },
    { rank: 245, cyrillic: "искате", latin: "iskate", phonetic: "eeskateh", englishmeaning: "you want" },
    { rank: 246, cyrillic: "скъпа", latin: "skapa", phonetic: "skuhpa", englishmeaning: "dear, expensive" },
    { rank: 247, cyrillic: "филм", latin: "film", phonetic: "feelm", englishmeaning: "film" },
    { rank: 248, cyrillic: "цена", latin: "tsena", phonetic: "tsehna", englishmeaning: "price" },
    { rank: 249, cyrillic: "любов", latin: "lyubov", phonetic: "lyubov", englishmeaning: "love" },
    { rank: 250, cyrillic: "шофьор", latin: "shofyor", phonetic: "shofyor", englishmeaning: "driver" }
  ];

  const HIKING_WORD_SOURCE = [
    { rank: 1, cyrillic: "влак", latin: "vlak", phonetic: "vlak", englishmeaning: "train" },
    { rank: 2, cyrillic: "автобус", latin: "avtobus", phonetic: "avtoboos", englishmeaning: "bus" },
    { rank: 3, cyrillic: "закъснение", latin: "zakasnenie", phonetic: "zakuhsnehneeeh", englishmeaning: "delay" },
    { rank: 4, cyrillic: "спешен случай", latin: "speshen sluchay", phonetic: "spehshehn sloochay", englishmeaning: "emergency" },
    { rank: 5, cyrillic: "гръм", latin: "gram", phonetic: "gruhm", englishmeaning: "thunder" },
    { rank: 6, cyrillic: "лошо време", latin: "losho vreme", phonetic: "losho vrehmeh", englishmeaning: "bad weather" },
    { rank: 7, cyrillic: "крака", latin: "kraka", phonetic: "kraka", englishmeaning: "feet" },
    { rank: 8, cyrillic: "уморен", latin: "umoren", phonetic: "oomorehn", englishmeaning: "tired" },
    { rank: 9, cyrillic: "отпочинал", latin: "otpochinal", phonetic: "otpocheenal", englishmeaning: "well rested" },
    { rank: 10, cyrillic: "свеж", latin: "svezh", phonetic: "svehzh", englishmeaning: "fresh" },
    { rank: 11, cyrillic: "вода", latin: "voda", phonetic: "voda", englishmeaning: "water" },
    { rank: 12, cyrillic: "планина", latin: "planina", phonetic: "planeena", englishmeaning: "mountain" },
    { rank: 13, cyrillic: "пътека", latin: "pateka", phonetic: "puhtehka", englishmeaning: "trail" },
    { rank: 14, cyrillic: "змия", latin: "zmiya", phonetic: "zmeeya", englishmeaning: "snake" },
    { rank: 15, cyrillic: "овчарско куче", latin: "ovcharsko kuche", phonetic: "ovcharsko koocheh", englishmeaning: "sheep dog" },
    { rank: 16, cyrillic: "кон", latin: "kon", phonetic: "kon", englishmeaning: "horse" },
    { rank: 17, cyrillic: "връх", latin: "vrah", phonetic: "vruhkh", englishmeaning: "mountain peak" },
    { rank: 18, cyrillic: "бобиком", latin: "bobikom", phonetic: "bobeekom", englishmeaning: "bobikom hut" },
    { rank: 19, cyrillic: "ком нова", latin: "kom nova", phonetic: "kom nova", englishmeaning: "kom hut new" },
    { rank: 20, cyrillic: "ком стара", latin: "kom stara", phonetic: "kom stara", englishmeaning: "kom hut old" },
    { rank: 21, cyrillic: "петрохан", latin: "petrohan", phonetic: "pehtrokhan", englishmeaning: "petrohan creative house" },
    { rank: 22, cyrillic: "пробойница", latin: "proboynitsa", phonetic: "proboyneetsa", englishmeaning: "proboynitsa hut" },
    { rank: 23, cyrillic: "тръстеная", latin: "trastenaya", phonetic: "truhstehnaya", englishmeaning: "trastenaya hut" },
    { rank: 24, cyrillic: "лескова", latin: "leskova", phonetic: "lehskova", englishmeaning: "leskova hut" },
    { rank: 25, cyrillic: "мургаш", latin: "murgash", phonetic: "moorgash", englishmeaning: "murgash hut" },
    { rank: 26, cyrillic: "чавдар", latin: "chavdar", phonetic: "chavdar", englishmeaning: "chavdar hut" },
    { rank: 27, cyrillic: "мургана", latin: "murgana", phonetic: "moorgana", englishmeaning: "murgana hut" },
    { rank: 28, cyrillic: "кашана", latin: "kashana", phonetic: "kashana", englishmeaning: "kashana hut" },
    { rank: 29, cyrillic: "свищиплаз", latin: "svishtiplaz", phonetic: "sveeshteeplaz", englishmeaning: "svishtiplaz hut" },
    { rank: 30, cyrillic: "момина поляна", latin: "momina polyana", phonetic: "momeena polyana", englishmeaning: "momina polyana hut" },
    { rank: 31, cyrillic: "иванина поляна", latin: "ivanina polyana", phonetic: "eevaneena polyana", englishmeaning: "ivanina polyana hut" },
    { rank: 32, cyrillic: "бенковски", latin: "benkovski", phonetic: "behnkovskee", englishmeaning: "benkovski hut" },
    { rank: 33, cyrillic: "вежен", latin: "vezhen", phonetic: "vehzhehn", englishmeaning: "vezhen hut" },
    { rank: 34, cyrillic: "хижа ехо", latin: "hizha eho", phonetic: "kheezha ehkho", englishmeaning: "echo hut" },
    { rank: 35, cyrillic: "хижа козята стена", latin: "hizha kozyata stena", phonetic: "kheezha kozyata stehna", englishmeaning: "kozya stena hut" },
    { rank: 36, cyrillic: "заслон орлово гнездо", latin: "zaslon orlovo gnezdo", phonetic: "zaslon orlovo gnehzdo", englishmeaning: "orlovo gnezdo shelter" },
    { rank: 37, cyrillic: "пешова мъка", latin: "peshova maka", phonetic: "pehshova muhka", englishmeaning: "peshova muka hut" },
    { rank: 38, cyrillic: "дерменка", latin: "dermenka", phonetic: "dehrmehnka", englishmeaning: "dermenka hut" },
    { rank: 39, cyrillic: "добрила", latin: "dobrila", phonetic: "dobreela", englishmeaning: "dobrila hut" },
    { rank: 40, cyrillic: "заслон амбарица", latin: "zaslon ambaritsa", phonetic: "zaslon ambareetsa", englishmeaning: "ambaritsa shelter" },
    { rank: 41, cyrillic: "хижа васил левски", latin: "hizha vasil levski", phonetic: "kheezha vaseel lehvskee", englishmeaning: "vasil levski hut" },
    { rank: 42, cyrillic: "заслон ботев", latin: "zaslon botev", phonetic: "zaslon botehv", englishmeaning: "botev shelter" },
    { rank: 43, cyrillic: "заслон маринка", latin: "zaslon marinka", phonetic: "zaslon mareenka", englishmeaning: "marinka shelter" },
    { rank: 44, cyrillic: "заслон михайлов", latin: "zaslon mihaylov", phonetic: "zaslon meekhaylov", englishmeaning: "mihaylov shelter" },
    { rank: 45, cyrillic: "тъжа", latin: "tazha", phonetic: "tuhzha", englishmeaning: "tazha hut" },
    { rank: 46, cyrillic: "мандрата", latin: "mandrata", phonetic: "mandrata", englishmeaning: "mandrata hut" },
    { rank: 47, cyrillic: "мазалат", latin: "mazalat", phonetic: "mazalat", englishmeaning: "mazalat hut" },
    { rank: 48, cyrillic: "партизанска песен", latin: "partizanska pesen", phonetic: "parteezanska pehsehn", englishmeaning: "partizanska pesen hut" },
    { rank: 49, cyrillic: "узана", latin: "uzana", phonetic: "oozana", englishmeaning: "uzana hut" },
    { rank: 50, cyrillic: "бузлуджа стара", latin: "buzludzha stara", phonetic: "boozloodzha stara", englishmeaning: "buzludzha hut old" },
    { rank: 51, cyrillic: "бузлуджа нова", latin: "buzludzha nova", phonetic: "boozloodzha nova", englishmeaning: "buzludzha hut new" },
    { rank: 52, cyrillic: "българка", latin: "balgarka", phonetic: "buhlgarka", englishmeaning: "balgarka hut" },
    { rank: 53, cyrillic: "планинец", latin: "planinets", phonetic: "planeenehts", englishmeaning: "planinets hut" },
    { rank: 54, cyrillic: "кръстец", latin: "krastets", phonetic: "kruhstehts", englishmeaning: "krastets hut" },
    { rank: 55, cyrillic: "грамадлива", latin: "gramadliva", phonetic: "gramadleeva", englishmeaning: "gramadliva hut" },
    { rank: 56, cyrillic: "химик", latin: "himik", phonetic: "kheemeek", englishmeaning: "himik hut" },
    { rank: 57, cyrillic: "предела", latin: "predela", phonetic: "prehdehla", englishmeaning: "predela hut" },
    { rank: 58, cyrillic: "заслон караиваново хорище", latin: "zaslon karaivanovo horishte", phonetic: "zaslon karaeevanovo khoreeshteh", englishmeaning: "karaivanovo horishte shelter" },
    { rank: 59, cyrillic: "буковец", latin: "bukovets", phonetic: "bookovehts", englishmeaning: "bukovets hut" },
    { rank: 60, cyrillic: "чумерна", latin: "chumerna", phonetic: "choomehrna", englishmeaning: "chumerna hut" },
    { rank: 61, cyrillic: "заслон вратник", latin: "zaslon vratnik", phonetic: "zaslon vratneek", englishmeaning: "vratnik shelter" },
    { rank: 62, cyrillic: "върбишки проход", latin: "varbishki prohod", phonetic: "vuhrbeeshkee prokhod", englishmeaning: "varbishki pass hut" },
    { rank: 63, cyrillic: "заслон хазим горския", latin: "zaslon hazim gorskiya", phonetic: "zaslon khazeem gorskeeya", englishmeaning: "hazim gorskiya shelter" },
    { rank: 64, cyrillic: "хижа топчийско", latin: "hizha topchiysko", phonetic: "kheezha topcheeysko", englishmeaning: "topchiysko hut" },
    { rank: 65, cyrillic: "козичино", latin: "kozichino", phonetic: "kozeecheeno", englishmeaning: "kozichino tourist dormitory" },
    { rank: 66, cyrillic: "емона", latin: "emona", phonetic: "ehmona", englishmeaning: "emona area near cape emine" },
    { rank: 67, cyrillic: "фенерче", latin: "fenerche", phonetic: "fehnehrcheh", englishmeaning: "flashlight" },
    { rank: 68, cyrillic: "термобельо", latin: "termobelyo", phonetic: "tehrmobehlyo", englishmeaning: "thermal underwear" },
    { rank: 69, cyrillic: "южен склон", latin: "yuzhen sklon", phonetic: "yuzhehn sklon", englishmeaning: "southern slope" },
    { rank: 70, cyrillic: "пещера", latin: "peshtera", phonetic: "pehshtehra", englishmeaning: "cave" },
    { rank: 71, cyrillic: "нощувка", latin: "noshtuvka", phonetic: "noshtoovka", englishmeaning: "overnight stay" },
    { rank: 72, cyrillic: "филтър за вода", latin: "filtar za voda", phonetic: "feeltuhr za voda", englishmeaning: "water filter" },
    { rank: 73, cyrillic: "слънцезащита", latin: "slantsezashtita", phonetic: "sluhntsehzashteeta", englishmeaning: "sun protection" },
    { rank: 74, cyrillic: "каньон", latin: "kanyon", phonetic: "kanyon", englishmeaning: "canyon" },
    { rank: 75, cyrillic: "южен вятър", latin: "yuzhen vyatar", phonetic: "yuzhehn vyatuhr", englishmeaning: "southern wind" },
    { rank: 76, cyrillic: "шофьор", latin: "shofyor", phonetic: "shofyor", englishmeaning: "driver" },
    { rank: 77, cyrillic: "чайник", latin: "chaynik", phonetic: "chayneek", englishmeaning: "kettle" },
    { rank: 78, cyrillic: "южен маршрут", latin: "yuzhen marshrut", phonetic: "yuzhehn marshroot", englishmeaning: "southern route" },
    { rank: 79, cyrillic: "югоизточен склон", latin: "yugoiztochen sklon", phonetic: "yugoeeztochehn sklon", englishmeaning: "southeastern slope" },
    { rank: 80, cyrillic: "термофолио", latin: "termofolio", phonetic: "tehrmofoleeo", englishmeaning: "emergency thermal blanket" },
    { rank: 81, cyrillic: "флисово яке", latin: "flisovo yake", phonetic: "fleesovo yakeh", englishmeaning: "fleece jacket" },
    { rank: 82, cyrillic: "каньонинг", latin: "kanyoning", phonetic: "kanyoneeng", englishmeaning: "canyoning" },
    { rank: 83, cyrillic: "планински водач", latin: "planinski vodach", phonetic: "planeenskee vodach", englishmeaning: "mountain guide" },
    { rank: 84, cyrillic: "чешма", latin: "cheshma", phonetic: "chehshma", englishmeaning: "water source" },
    { rank: 85, cyrillic: "искам нощувка", latin: "iskam noshtuvka", phonetic: "eeskam noshtoovka", englishmeaning: "I want a place to sleep" },
    { rank: 86, cyrillic: "стръмно", latin: "stramno", phonetic: "'struhm-no", englishmeaning: "steep, steeply" },
    { rank: 87, cyrillic: "обрасло", latin: "obraslo", phonetic: "obraslo", englishmeaning: "overgrown" }
  ];

  const ALPHABET_WORD_SOURCE = [
    { rank: 1, cyrillic: "а", latin: "a", phonetic: "a", englishmeaning: "Cyrillic letter а" },
    { rank: 2, cyrillic: "б", latin: "b", phonetic: "b", englishmeaning: "Cyrillic letter б" },
    { rank: 3, cyrillic: "в", latin: "v", phonetic: "v", englishmeaning: "Cyrillic letter в" },
    { rank: 4, cyrillic: "г", latin: "g", phonetic: "g", englishmeaning: "Cyrillic letter г" },
    { rank: 5, cyrillic: "д", latin: "d", phonetic: "d", englishmeaning: "Cyrillic letter д" },
    { rank: 6, cyrillic: "е", latin: "e", phonetic: "eh", englishmeaning: "Cyrillic letter е" },
    { rank: 7, cyrillic: "ж", latin: "zh", phonetic: "zh", englishmeaning: "Cyrillic letter ж" },
    { rank: 8, cyrillic: "з", latin: "z", phonetic: "z", englishmeaning: "Cyrillic letter з" },
    { rank: 9, cyrillic: "и", latin: "i", phonetic: "ee", englishmeaning: "Cyrillic letter и" },
    { rank: 10, cyrillic: "й", latin: "y", phonetic: "y", englishmeaning: "Cyrillic letter й" },
    { rank: 11, cyrillic: "к", latin: "k", phonetic: "k", englishmeaning: "Cyrillic letter к" },
    { rank: 12, cyrillic: "л", latin: "l", phonetic: "l", englishmeaning: "Cyrillic letter л" },
    { rank: 13, cyrillic: "м", latin: "m", phonetic: "m", englishmeaning: "Cyrillic letter м" },
    { rank: 14, cyrillic: "н", latin: "n", phonetic: "n", englishmeaning: "Cyrillic letter н" },
    { rank: 15, cyrillic: "о", latin: "o", phonetic: "o", englishmeaning: "Cyrillic letter о" },
    { rank: 16, cyrillic: "п", latin: "p", phonetic: "p", englishmeaning: "Cyrillic letter п" },
    { rank: 17, cyrillic: "р", latin: "r", phonetic: "r", englishmeaning: "Cyrillic letter р" },
    { rank: 18, cyrillic: "с", latin: "s", phonetic: "s", englishmeaning: "Cyrillic letter с" },
    { rank: 19, cyrillic: "т", latin: "t", phonetic: "t", englishmeaning: "Cyrillic letter т" },
    { rank: 20, cyrillic: "у", latin: "u", phonetic: "oo", englishmeaning: "Cyrillic letter у" },
    { rank: 21, cyrillic: "ф", latin: "f", phonetic: "f", englishmeaning: "Cyrillic letter ф" },
    { rank: 22, cyrillic: "х", latin: "h", phonetic: "kh", englishmeaning: "Cyrillic letter х" },
    { rank: 23, cyrillic: "ц", latin: "ts", phonetic: "ts", englishmeaning: "Cyrillic letter ц" },
    { rank: 24, cyrillic: "ч", latin: "ch", phonetic: "ch", englishmeaning: "Cyrillic letter ч" },
    { rank: 25, cyrillic: "ш", latin: "sh", phonetic: "sh", englishmeaning: "Cyrillic letter ш" },
    { rank: 26, cyrillic: "щ", latin: "sht", phonetic: "sht", englishmeaning: "Cyrillic letter щ" },
    { rank: 27, cyrillic: "ъ", latin: "a", phonetic: "uh", englishmeaning: "Cyrillic letter ъ" },
    { rank: 28, cyrillic: "ь", latin: "y", phonetic: "y", englishmeaning: "Cyrillic letter ь" },
    { rank: 29, cyrillic: "ю", latin: "yu", phonetic: "yu", englishmeaning: "Cyrillic letter ю" },
    { rank: 30, cyrillic: "я", latin: "ya", phonetic: "ya", englishmeaning: "Cyrillic letter я" }
  ];

  window.CYRILLIC_TRAINER_DATA = {
    source: {
      wordFrequency: "https://github.com/hermitdave/FrequencyWords/blob/master/content/2018/bg/bg_50k.txt",
      hikingHuts: "https://kom-emine.bg/huts-all-en/?lang=en",
      note: "Common ranks 247-250 replace less frequent source words to cover all lowercase Bulgarian Cyrillic letters."
    },
    letterTransliterations: LETTER_TRANSLITERATIONS,
    letterOptions: LETTER_OPTIONS,
    wordSource: WORD_SOURCE,
    datasets: [
      { id: "1", label: "top 250 words", wordSource: WORD_SOURCE },
      { id: "2", label: "Hiking E3 Kom-Emine words", wordSource: HIKING_WORD_SOURCE },
      { id: "3", label: "alphabet letters", wordSource: ALPHABET_WORD_SOURCE }
    ]
  };
}());
